### ISSUE TITLE
Remove chrN_random,ChrUn,chrM mapped reads before using MACS2.

### ISSUE THREAD

**Issue by CTLife** [taoliu/MACS#104]
Hi, Dr Liu, 
   Is it necessary for peak calling of histone modifications ChIP-seq data to remove the mapped reads on chrN_random, ChrUn and chrM  before running MACS2?
  Thank you!

**Comment by taoliu** [comment]
You'd better do so. This will avoid unnecessary computation and unexpected errors.

**Comment by CTLife** [comment]
OK, thank you.
