### ISSUE TITLE
Can't detect format!

### ISSUE THREAD

**Issue by adcwilliams** [taoliu/MACS#107]
Apparently this may be related to an old issue:

http://seqanswers.com/forums/archive/index.php/t-12150.html

Is this still an issue with large files? Here's the traceback:

Command line: callpeak -t /scratch/sisaw7/macs2/2015-07-09/input/chipseq/GSM1601721_STAT3_WT_nc_1685.peaks.bedgraph --nomodel -B -g mm --outdir /scratch/sisaw7/macs2/2015-07-09/output/GSM1601721_STAT3_WT_nc_1685.peaks/macs2/ -n GSM1601721_STAT3_WT_nc_1685.peaks.macs2 -B -q 0.01
ARGUMENTS LIST:
name = GSM1601721_STAT3_WT_nc_1685.peaks.macs2
format = AUTO
ChIP-seq file = ['/scratch/sisaw7/macs2/2015-07-09/input/chipseq/GSM1601721_STAT3_WT_nc_1685.peaks.bedgraph']
control file = None
effective genome size = 1.87e+09
band width = 300
model fold = [5, 50]
qvalue cutoff = 1.00e-02
Larger dataset will be scaled towards smaller dataset.
Range for calculating regional lambda is: 10000 bps
Broad region calling is off
 
INFO  @ Tue, 22 Dec 2015 12:28:00: #1 read tag files... 
INFO  @ Tue, 22 Dec 2015 12:28:00: #1 read treatment tags... 
Exception ZeroDivisionError: 'integer division or modulo by zero' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
Exception ZeroDivisionError: 'integer division or modulo by zero' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
Exception ZeroDivisionError: 'integer division or modulo by zero' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
Exception IndexError: 'list index out of range' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
Exception IndexError: 'list index out of range' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
Traceback (most recent call last):
  File "/software/tools/pyenv/versions/2.7.9-macs2/bin/macs2", line 614, in <module>
    main()
  File "/software/tools/pyenv/versions/2.7.9-macs2/bin/macs2", line 56, in main
    run( args )
  File "/software/tools/pyenv/versions/2.7.9-macs2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 70, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/software/tools/pyenv/versions/2.7.9-macs2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 390, in load_tag_files_options
    tp = options.parser(options.tfile[0], buffer_size=options.buffer_size)
  File "MACS2/IO/Parser.pyx", line 68, in MACS2.IO.Parser.guess_parser (MACS2/IO/Parser.c:2754)
  File "MACS2/IO/Parser.pyx", line 102, in MACS2.IO.Parser.guess_parser (MACS2/IO/Parser.c:2645)
Exception: Can't detect format!

**Comment by sitag** [comment]
It looks like you are using bedgraph - `/scratch/sisaw7/macs2/2015-07-09/input/chipseq/GSM1601721_STAT3_WT_nc_1685.peaks.bedgraph` - I don't think bedgraph is supported. Bedgraph doesn't contain read level information which is what MACS needs I think.

**Comment by taoliu** [comment]
@sitag is right! You can't call peaks from a final result file containing only peaks. For this GSM1601721, You need to retrieve the corresponding SRA datasets, convert them to fastq files, do the alignment on reference genome, then call peaks using MACS2.

**Comment by taoliu** [comment]
Close due to inactivity. Reopen if needed.
