### ISSUE TITLE
Full fragment bed file support

### ISSUE THREAD

**Issue by ashleywoodfin** [taoliu/MACS#112]
We would like to pass macs a bedfile that represents entire fragments. This would mean passing a bed file where the paired end data has been already mapped and converted into a "fragment" bed format, such as:

`chr start (of fragment) end (of fragment)`

We do exclusively paired end data, but we do not save the bulky bam files and instead convert directly into this fragment bed format. We are currently using an in house peak caller, but we would really like to use Macs and love to add you to our citations ;)

We have tried to trick Macs by converting our fragment bed to the paired end bed format (that is unfortunately poorly documented) and then back to bam. However, we were not successful and it anyhow seems overly circular. Since you already have an option that could be tweaked for single-end bedfile format could it be changed to not estimate the fragment length and use the entire start stop region rather than the beginning?

Many thanks,
Ashley

**Comment by taoliu** [comment]
Hi Ashley, I will try to implement the feature you asked for. Will keep you updated.

**Comment by ashleywoodfin** [comment]
Great! If we can help with any testing, please let me know.

Many thanks,
Ashley

**Comment by taoliu** [comment]
@ashleywoodfin Could you test if the current MACS2 codes can solve your question? I haven't released a package on PyPI, so you need to 'clone' MACS2 from the github, make sure 'cython' is installed, then run 'python setup_w_cython.py install' to install this new version.

**Comment by ashleywoodfin** [comment]
@taoliu I tested the new BEDPE on few of our different datasets, and it works great! 

All the best,
Ashley

**Comment by taoliu** [comment]
@ashleywoodfin Great! Then I will release a new version officially on PYPI website.
