### ISSUE TITLE
'effective genome size' , how precisse does it have to be?

### ISSUE THREAD

**Issue by biocyberman** [taoliu/MACS#116]
Rat genome is one of the genomes that are not mentioned very much among macs2 users. So I had to look around and do some work for myself. I want to share the output and also ask a related question.

I used rat genome rn6 downloaded from UCSC bigzip file and kept all contigs that do not have standard chromosome names.  The calculation involved using `gem-indexer` for base-space data and  `gem-mappability` with kmer size of 45, 50, 75, 100, and 150 bases. The effective genome size values are the number of '!' characters in the `.mappability` files.   

```text
rn6.softmask.all_45: 2105347242
rn6.softmask.all_50: 2081721273
rn6.softmask.all_75: 2197995070
rn6.softmask.all_100: 2247394146
rn6.softmask.all_150: 2285452802
```

I also did some test with color-space index of only chromosome 1. The numbers looks greater than that from base-space index of chromosome 1. So here comes some questions.

1. Which number should I use? The one from color-space index or base-space index. My BAM files were aligned with colorspace aligner and reads are colorspace reads.

2. What is the consequence of under or over estimate the effective genome size in macs2 output? 

3. Macs2 documentation does not seem to draw much attention about kmer size. What kmer size was used to calculate those values for 'supported' genomes by macs2?

Thanks.

**Comment by biocyberman** [comment]
Decided to post the questions to biostars for broader audience.

**Comment by hreypar** [comment]
So what did you end up using in the end? and how come no one knows the MACS2 kmer size used to compute effective genome size in the supported genomes? :(

**Comment by taoliu** [comment]
@hreypar The fact is that the "effective genome size" is used to compute genome-wide background. And in the actual peak calling, this background is usually the smallest among the three "local background" ( including 10k, 100k, and peak size surrounding region) estimated from control data. Moreover, a slight difference in the estimated number, such as 10% difference, wouldn't cause a big impact on peak calling -- assuming that the data is in good quality and you are mainly studying top tens of thousands of peaks. As a general suggestion, the effective genome size number for MACS2 can be calculated as "the genome size - simple repeats - Ns". Although you can always use a k-mer method to accurately estimate or fine-tuning the number for you specific dataset.
