### ISSUE TITLE
MACS2 to CEAS

### ISSUE THREAD

**Issue by spenceryang2017** [taoliu/MACS#117]
Hi Tao,

After MACS2, I want to run CEAS, and I found MACS2 give bdg and narrowpeak, so how can I change bdg to wig file and narrowpeak to bed file? I tried to run MACS and got bed and wig, but the peaks in MACS and MACS2 were different, I also tried use bdg and narrowpeak to run CEAS, it failed.
Thank you

Spencer

**Comment by taoliu** [comment]
There is a special version of CEAS which supports bigwig file [https://bitbucket.org/cistrome/cistrome-applications-harvard/src/7bcbf7953a8b46392fa8580969d7671df6f84364/published-packages/CEAS/?at=default]. You can convert bdg to bigwig using this script: https://gist.github.com/taoliu/2469050. After install the new CEAS, use the 'ceasBW' command instead.

**Comment by taoliu** [comment]
Close since it's not related to MACS.
