### ISSUE TITLE
Issue install MACS2 mac

### ISSUE THREAD

**Issue by djevo1** [taoliu/MACS#118]
I am getting an issue when trying to install from source or pip. This is what I get

`Collecting MACS2
  Using cached MACS2-2.1.1.20160226.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6 in /Library/Python/2.7/site-packages (from MACS2)
Building wheels for collected packages: MACS2
  Running setup.py bdist_wheel for MACS2 ... error
  Complete output from command /Users/evanclark/Desktop/caputiclip/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/dr/07m1vc7x12n97h5p4zw_vlpw0000gn/T/pip-build-1hgEkD/MACS2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/dr/07m1vc7x12n97h5p4zw_vlpw0000gn/T/tmpPGbCk2pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.8-intel-2.7
  creating build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/__init__.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/bdgbroadcall_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/bdgcmp_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/bdgdiff_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/bdgopt_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/bdgpeakcall_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/callpeak_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/cmbreps_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/Constants.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/diffpeak_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/filterdup_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/OptValidator.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/OutputWriter.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/pileup_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/predictd_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/randsample_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  copying MACS2/refinepeak_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
  creating build/lib.macosx-10.8-intel-2.7/MACS2/IO
  copying MACS2/IO/__init__.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
  copying MACS2/IO/BinKeeper.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
  copying MACS2/IO/test_processing.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
  copying MACS2/IO/test_threading.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
  running build_ext
  building 'MACS2.Prob' extension
  creating build/temp.macosx-10.8-intel-2.7
  creating build/temp.macosx-10.8-intel-2.7/MACS2
  clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/Library/Python/2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c MACS2/Prob.c -o build/temp.macosx-10.8-intel-2.7/MACS2/Prob.o -w -O3 -ffast-math
  clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
  clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for MACS2
  Running setup.py clean for MACS2
Failed to build MACS2
Installing collected packages: MACS2
  Running setup.py install for MACS2 ... error
    Complete output from command /Users/evanclark/Desktop/caputiclip/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/dr/07m1vc7x12n97h5p4zw_vlpw0000gn/T/pip-build-1hgEkD/MACS2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dr/07m1vc7x12n97h5p4zw_vlpw0000gn/T/pip-7yMtJ3-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/evanclark/Desktop/caputiclip/venv/include/site/python2.7/MACS2:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.8-intel-2.7
    creating build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/__init__.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/bdgbroadcall_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/bdgcmp_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/bdgdiff_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/bdgopt_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/bdgpeakcall_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/callpeak_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/cmbreps_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/Constants.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/diffpeak_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/filterdup_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/OptValidator.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/OutputWriter.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/pileup_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/predictd_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/randsample_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    copying MACS2/refinepeak_cmd.py -> build/lib.macosx-10.8-intel-2.7/MACS2
    creating build/lib.macosx-10.8-intel-2.7/MACS2/IO
    copying MACS2/IO/__init__.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
    copying MACS2/IO/BinKeeper.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
    copying MACS2/IO/test_processing.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
    copying MACS2/IO/test_threading.py -> build/lib.macosx-10.8-intel-2.7/MACS2/IO
    running build_ext
    building 'MACS2.Prob' extension
    creating build/temp.macosx-10.8-intel-2.7
    creating build/temp.macosx-10.8-intel-2.7/MACS2
    clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/Library/Python/2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c MACS2/Prob.c -o build/temp.macosx-10.8-intel-2.7/MACS2/Prob.o -w -O3 -ffast-math
    clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
    clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
    error: command 'clang' failed with exit status 1`

**Comment by taoliu** [comment]
Hi @djevo1 , what't the version of your Mac OS X and clang and python? For your information, I am using Mac to develop MACS2 so if you are using the newest version of Mac OS X (10.11.3), the default python installed natively with the OS (2.7.10), and clang (Apple LLVM version 7.0.2 (clang-700.1.81)) from the matching Xcode suite(7.2.1), then you shouldn't have any problem with installing MACS2 through 'pip install MACS2'. Judging from your error message, there must be different python versions installed in your system.

**Comment by djevo1** [comment]
I am using MAC OS 10.8.5, and I installed python 3.5, but it appears as 
if the virtualenv is using 2.7.

Tao Liu (τν) wrote:

**Comment by taoliu** [comment]
@djevo1 I don't think it was Python 3.5 since your error message showed '2.7'. MACS2 doesn't work on Python3 .  What about the version of clang and Xcode? It seems the error was from clang option: -mno-fused-madd. In MACS2 source code, there is no where mentioning the '-mno-fused-madd' option so there must be some discrepancies between the clang and the python you used.

**Comment by djevo1** [comment]
It was python 2.7 then, xcode is version 5.1.1, and clang version Apple 
LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.6.0


Tao Liu (τν) wrote:

**Comment by taoliu** [comment]
@djevo1 OK. I did some googling and found this: http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation-fa
Hope it helps!

**Comment by djevo1** [comment]
That fixed it. Thank You. And thank you for awesome tool!

Tao Liu (τν) wrote:
