### ISSUE TITLE
Please include the tempdir option in help file

### ISSUE THREAD

**Issue by biobenkj** [taoliu/MACS#148]
Using MACS on a shared HPC environment, it will fill up the tmp dir and result in some e-mails from the sysadmin. I see that the option exists in the callpeak_cmd.py source code and would be nice to add it to the help file and documentation as an option to redirect the temporary file write/read location.

Thanks!

**Comment by biobenkj** [comment]
Previous version man page? http://manpages.org/macs2_callpeak

**Comment by biobenkj** [comment]
This option doesn't exist on the latest release of MACS2? (pypi source)

**Comment by c-guzman** [comment]
Absolutely critical option required.

**Comment by biobenkj** [comment]
As a work around for the time being, you can modify the TEMPDIR/TEMP/TMP environment variable to point to an alternative temporary location to write files (this is untested but based on the function call to mkstemp: "The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables. There is thus no guarantee that the generated filename will have any nice properties, such as not requiring quoting when passed to external commands via os.popen()."

Setting up a pull request to add the option back to the software.

**Comment by c-guzman** [comment]
Running:
```

export $TMPDIR=$(mktemp -d)
<script>
rm -rf $TMPDIR
```

works.

PS: This is for a Nextflow pipeline, but it should work similarly for anything else.

**Comment by taoliu** [comment]
Right. I forgot to mention this option in the README file which manpage is based on. On command line, if you type 'macs2 callpeak --help', you will see:

  --tempdir TEMPDIR     Optional directory to store temp files. DEFAULT: XXX/XXX/tmp

**Comment by biobenkj** [comment]
Unfortunately, when I run:

    macs2 callpeak --help

It does not display the --tempdir option. The version I am using is via an anaconda install, version macs2 2.1.0.20150731.

**Comment by biobenkj** [comment]
To be clear, this is the Anaconda2 install and the latest version of macs2 is for python3 correct?

**Comment by taoliu** [comment]
@biobenkj This option can be found in the latest release on PyPI, version 2.1.1 20160309. Older versions, such as your 2.1.0, don't have such option. Also, I am not aware of Anaconda2, but I remember previously there is a bug in the math libraries in Anaconda. MACS2 is not ready for Python3, only for Python2.7.

**Comment by biobenkj** [comment]
Anaconda is a package manager for python: https://www.continuum.io/downloads

The latest version exists for the package manager (recently updated) but think this is a relevant issue for anyone using an older version to re-direct their temp directory based on @c-guzman comment. Feel free to close the issue since this is resolved in the latest version of MACS2
