### ISSUE TITLE
link to download PeakSplitter 

### ISSUE THREAD

**Issue by dorothyzh** [taoliu/MACS#152]
Hi, 

I've faced a problem when I try to use --call-subpeaks​

The ERROR file gave me the warning like this:  
ERROR:root:Please download PeakSplitter from <http://www.ebi.ac.uk/bertone/software/PeakSplitter_Cpp.tar.gz>.

When I tried to download the PeakSplitter_Cpp.tar.gz, this link was failed. For it seems like the website has moved this software to another place, shown below:
http://www.ebi.ac.uk/sites/ebi.ac.uk/files/groups/bertone/software/PeakSplitter_Cpp_1.0.tar.gz

**Comment by taoliu** [comment]
I will fix that. Thanks! On the other hand, you can try MACS2 which has its own subpeak calling function.

**Comment by taoliu** [comment]
Fixed in a662072

**Comment by dorothyzh** [comment]
OK, thanks a lot~~~~ I like this software~~


Huan

**Comment by dorothyzh** [comment]
Hi Tao,

It seems like MACS2 and MACS14 are totally different softwares, based on
different model?
If I am studying the TFs, with single-end DNA seq reads, which one do you
prefer me to use?

Besides, I do not have input, I only have control and mutant, so could I
use control as input when using the macs?


Thanks so much in advance!

Best,

Huan ZHONG

**Comment by taoliu** [comment]
Yes. You can just use your control (a mock-IP sample?) I would alway suggest you to use MACS2 instead of MACS14 since the older one is not optimized for the current sequencing technologies. If the sequencing depth is high, MACS14 would behave strangely.

**Comment by dorothyzh** [comment]
?OK, I've got it.


Thanks so much!


Huan

________________________________
发件人: Tao Liu (τν) <notifications@github.com>
发送时间: 2017年3月22日 12:14
收件人: taoliu/MACS
抄送: Zhong, Huan; Author
主题: Re: [taoliu/MACS] link to download PeakSplitter (#152)


Yes. You can just use your control (a mock-IP sample?) I would alway suggest you to use MACS2 instead of MACS14 since the older one is not optimized for the current sequencing technologies. If the sequencing depth is high, MACS14 would behave strangely.

―
