### ISSUE TITLE
q-value confusion

### ISSUE THREAD

**Issue by sklasfeld** [taoliu/MACS#175]
When I run MACS2 callpeak I use the -q function to filter for peaks with q-values less than 10^-10. However, I get more peaks when I filter for -q .01 and then manually filter for 10^-10 using the following command:
`awk '{print exp($9*-log(10));}' MACS_peaks.narrowPeak | awk '$1<10^-10'| wc -l`
Why would this be the case?

**Comment by taoliu** [comment]
When you set -q during callpeak process, the cutoff is applied to the whole peak region. Whereas when you look at the q value in the output, that value is for 'peak summit'.

**Comment by sklasfeld** [comment]
What is the q-value in the .broadPeak files then? Since you said that the 9th column in the narrowPeak files stand for the q-values of the summit and broadPeaks do not have summits is the q-values in broadPeak files the same as the one used for filtering in the command line? If not, what does it stand for?

**Comment by taoliu** [comment]
As for broad peak, the q-value assigned to peak is the mean value in the peak region. I will clarify this in MACS2 document.

**Comment by sklasfeld** [comment]
Could you clarify which value you get the mean of? Do you get the q-value of every base pair in each peak compared to the control and then take the mean?

**Comment by taoliu** [comment]
@sklasfeld Yes. A p-value is assigned to each base pair, then mean value will be taken by considering every base pair in the peak region.

**Comment by sklasfeld** [comment]
Okay that makes sense! Thank you!

**Comment by taoliu** [comment]
Updated the README.
