### ISSUE TITLE
Q: why python 2.7 precisely?

### ISSUE THREAD

**Issue by lzamparo** [taoliu/MACS#179]
I'm using MACS as part of my pipeline, but was surprised to find it's 2.7 only.  Not 2.6, not 2.8, not anything near python3.  I'm contemplating a port to python 3.5, but would like to ask if there is some major impediment which would complicate this process?

Thanks in advance,

**Comment by taoliu** [comment]
Hi @lzamparo We are working on porting MACS2 to python3. The reason we required 2.7 is due to our limited ability to test the software.

**Comment by lzamparo** [comment]
Thanks for the reply.  I tried porting it myself, but got bogged down in slowly pushing tests forward.  Even after using tools like python-modernize to try and accelerate the process, the subcommands that I did manage to get running in a syntactically correct manner (all the callpeak varieties) didn't produce test output that matched the 2.7 version.  

I later found (but haven't tried) your development branch starting the port to python 3.  I'm not sure how far you've come, but if you're welcome to my py3 version.  I can submit it as a PR to the PortTo3 branch if you like.  If not, feel free to close this issue.

**Comment by cokelaer** [comment]
Out of curiosity, i wanted to know if the portage to python 3 was on-going and whether there was a timeline to make it available. I may be able to help if required (e.g. for testing)

**Comment by rlegendre** [comment]
I'm very interested in a macs2 compatible with python3, could you tell me if it will be soon available? thanks

**Comment by evanbiederstedt** [comment]
Could MACS2 please become Python3.x compatible soon? 
It looks like porting this to Python3.x should be fairly straightforward and painless given the source code, but it's good if the developers do this, as MACS2 is a dependency for other bioinformatics tools (which are currently hampered from porting to Python3.x because of this.)

Thanks

**Comment by lzamparo** [comment]
@evanbiederstedt it was anything but straightforward and painless, in my experience.  Rather the opposite.  The codebase has a lot of python 2 in cythonized code which complicates things, and is not touched by any automated conversion tools.

**Comment by evanbiederstedt** [comment]
> The codebase has a lot of python 2 in cythonized code which complicates things, and is not touched by any automated conversion tools.

I'm a bit confused. You mean there is cythonized Python2.x code without the original Python2.x scripts which were cythonized? If these scripts exists, I would simply convert them to Python3.x and run them through Cython. (If these don't exist, perhaps the developers could provide them.) If significant hardcoding was done with Cython, then I suspect this would take more time/pain.

**Comment by taoliu** [comment]
Still need some time to convert our python2 code to python3. The main reason is that the string type is different in Python3 compared with python2. Since we are dealing with sequencing data, it’s not necessary to assume everything is encoded in UTF-8, for example. To make the program more efficient, it would be better to use bytes/bytearray type in Python3 as much as we can.  There is no issue with Cython. I am using Python3 and Cython in another project without any problem. Just because MACS2 is originally written in Python2, I need to do some eyeballing to pick where I used character and string type…

Best,
Tao

**Comment by evanbiederstedt** [comment]
Hi Tao
Understood. This is usually the biggest hurdle to jump over when porting to Python3.x. 
My rule of thumb is to use type `str` for encoded data, and `unicode` for unencoded data, and then the logic of porting to Python3.x is more straightforward.

Please make an announcement when this task is completed. Porting MACS2 has come up in other contexts, e.g. https://github.com/aryeelab/hichipper
Thanks

**Comment by lzamparo** [comment]
Hi Evan & Tao,

I'm not suggesting that cython cannot work with Python 3 (clearly it can).  I should be more precise.  I spent about two weeks converting the codebase to Python 3 compliance (cf [my branch here](https://github.com/lzamparo/MACS/tree/portTo3)), and after being able to run the tests for specifically `run_callpeak_narrow`under Python 3.5.2 to completion, I wanted to compare the results with those produced by MACS2 installed via conda under python 2.7.2.  The py2 results were very different from the py3 results, and it wasn't clear at that point where the bug(s) lay.  So I gave up, choosing instead to run a parallel install of python 2 in a conda env for MACS2 parts of any pipeline.  

If you're interested, I can make a gist showing the differences, maybe they'll be more informative for you?

**Comment by rioualen** [comment]
Hello, 
I'm also very interested in a python3-compatible version of Macs2, any recent update?
Thanks

**Comment by zhenyisong** [comment]
@taoliu Any progress towards to migrate the macs2 to py3? Seems two threads in the issue collection talked about this.  Otherwise, I have to re-deploy my code. Thanks again.

**Comment by taoliu** [comment]
Related to #242 . Now the Python3 compatible MACS v2.2.4 has been released.
