### ISSUE TITLE
MACS2- AttributeError: 'Namespace' object has no attribute 'tempdir'

### ISSUE THREAD

**Issue by subhashini-sadasivam** [taoliu/MACS#234]
Hello,

I am using MACS2 2.1.1.2016039 to analyse  test ChIP-Seq  data from Feng et al, 2012 Nature Protocols paper. I have installed MACS2 using PyPI on Linux machine under python 2.7.  I get the following error when I run callpeak 
macs2 callpeak -t HAIB_T47D_FoxA1.sam -g hs -n foxa1test 

Traceback (most recent call last):
File "/usr/bin/macs2", line 614, in <module>main()
File "/usr/bin/macs2", line 56, in main
run( args )
File "/home/venky/.local/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 68, in run
tempfile.tempdir = options.tempdir
AttributeError: 'Namespace' object has no attribute 'tempdir'

I have tried modifying the command to 
macs2 callpeak -t HAIB_T47D_FoxA1.sam -g hs -n foxa1test --tempdir ./TEMP
But this gives the error message “unrecognised arguments: --tempdir ./TEMP”.
Can you tell me how this issue can be solved? Thank you.

Sincerely,
Subhashini

**Comment by mortunco** [comment]
I had the exact problem with exact version of macs2. I removed macs2 from my machine with ```pip uninstall macs2``` then re installed it again. Solved to problem. Maybe you wanna try.

Good luck.
T.

**Comment by subhashini-sadasivam** [comment]
Thank you for your suggestion.
I installed macs2 from the source code. In the file, callpeak_cmd.py, I
modified line 68 from

tempfile.tempdir = options.tempdir
to
 #tempfile.tempdir = options.tempdir

This solved the problem.

**Comment by taoliu** [comment]
Hi @subhashini-sadasivam, the reason is that your computer has a "/usr/bin/macs2" which should come from certain official Linux distribution. Because users generally won't have permission to write to "/usr/bin/" directory. Uninstall that version (e.g. apt-get remove macs) and install a new version from source code would solve the problem even if you don't remove that line :)
