### ISSUE TITLE
Feat: move to python3

### ISSUE THREAD

**Issue by vivekbhr** [taoliu/MACS#242]
Hi @taoliu 

What are the plans for moving macs2 code to python3?

**Comment by andersgs** [comment]
It is almost too easy to do it these days: http://python-future.org/automatic_conversion.html

**Comment by taoliu** [comment]
Now there is a [new macs2python3 branch](/taoliu/MACS/macs2python3)  I am working on to migrate MASC2 to Python3. It has passed all my tests under the 'test' folder. If you are interested in, you can install it and test it using your data. It might throw some errors in other situations such as those related to string vs. bytes types.

**Comment by nsheff** [comment]
any update on macs2 working with python3 ? when I try to install it in python 3 it says: 

```
 Downloading https://files.pythonhosted.org/packages/5e/32/0108a85d9a91c18413e8492bea631725cdbc20b45970ef63e8d0020ef2da/MACS2-2.1.2.1.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 7.2MB/s 
    Complete output from command python setup.py egg_info:
    CRITICAL: Python version must be 2.7!
```

**Comment by afrendeiro** [comment]
I just tested the `macs2python3` branch with Python 3.7.3 and that works fine.
Any plans to merge the branch and submit to PyPI?

**Comment by whositwhatnow** [comment]
Where is the source for the python3 package?  It's not on PyPI yet and I woudl liek to test it out

**Comment by taoliu** [comment]
@afrendeiro I have to work on some testing scripts to test the branch `macs2python3`, and rebase this branch to the most recent `v2.1.2` codes.

**Comment by taoliu** [comment]
A new branch `feat_py3` has been created by merging most recent `master` and `macs2python3`: 5afe82a2fbbd830a7eef99025238496017a8a103

Work will be continued in the new branch...

**Comment by tillea** [comment]
A Python3 port would be very interesting for the Debian packaged version.  Debian is droping Python2 in the next release and we expect Python2 software to be removed in the not to distant future.
Kind regards, Andreas.

**Comment by taoliu** [comment]
MACS2 Python3 port is ready in the [feat_py3](/taoliu/MACS/tree/feat_py3) branch. Aim to release to PyPI by the end of this week.

**Comment by tillea** [comment]
On Tue, Oct 01, 2019 at 02:00:48PM -0700, Tao Liu (τν) wrote:
> MACS2 Python3 port is ready in the [feat_py3](/taoliu/MACS/tree/feat_py3) branch. Aim to release to PyPI by the end of this week.
Thanks a lot, Andreas.

**Comment by taoliu** [comment]
MACS v2.2.4 which is compatible with Python3 has been released. 

[Github](https://github.com/taoliu/MACS/releases/tag/v2.2.4)

[PyPI](https://pypi.org/project/MACS2/2.2.4/)

During the testing with [small datasets](/taoliu/MACS/tree/master/test), v2.2.4 generates the same results as v2.1.4. If you find any inconsistency on your datasets or have any comments, feel free to open a new issue. 

Thank everyone for your patience! I know that you are asking for a Python3 port of MACS for a long time.

**Comment by tillea** [comment]
On Thu, Oct 03, 2019 at 11:46:55AM -0700, Tao Liu (τν) wrote:
> MACS v2.2.4 which is compatible with Python3 has been released. 
Thanks a lot!

> During the testing with [small datasets](/taoliu/MACS/tree/master/test), v2.2.4 generates the same results as v2.1.4. If you find any inconsistency on your datasets or have any comments, feel free to open a new issue. 
The continuous integration test of the Debian package works as expected.

> Thank everyone for your patience! I know that you are asking for a Python3 port of MACS for a long time.
Its right in time - so thank you again, Andreas.

**Comment by taoliu** [comment]
@tillea You are welcome! And as a long-time Debian user, thank you so much for helping MACS integrated into Debian! By the way, I think now cython can be safely removed from the dependencies of MACS.

**Comment by tillea** [comment]
On Thu, Oct 03, 2019 at 12:41:26PM -0700, Tao Liu (τν) wrote:
> @tillea You are welcome! And as a long-time Debian user, thank you so much for helping MACS integrated into Debian!
:-)

> By the way, I think now cython can be safely removed from the dependencies of MACS.
Done in Git - thanks for the hint.
