### ISSUE TITLE
ATAC-seq short peaks calling

### ISSUE THREAD

**Issue by ritma001** [taoliu/MACS#250]
Dear all,

I am working with ATAC-seq data and I use MACS2  `-f BAMPE`  for the peak calling as suggested; however, only the unexpectedly short peak at 1 nucleotide was detected (as seen from chr start and end positions shown below). 

i.e. 
chr1    778830  778831  SRR2920477_1.Bowtie2Mapping_sorted_fdr1_summits_peak_1  32.30726
chr1    870077  870078  SRR2920477_1.Bowtie2Mapping_sorted_fdr1_summits_peak_2  7.02096
chr1    897421  897422  SRR2920477_1.Bowtie2Mapping_sorted_fdr1_summits_peak_3  9.74649
chr1    906924  906925  SRR2920477_1.Bowtie2Mapping_sorted_fdr1_summits_peak_4  25.38635

Prior to the peak calling, I converted the sam file to sorted bam format using samtools. I really doubt in which step I did wrong and possibly cause this problem. I could not find such an error posted elsewhere so, I decided to put a question here. Thank you in advance for your response. 

Wannisa

**Comment by IanCodes** [comment]
It looks like this is the summits.bed file, have you looked at the
peaks.xls file?

**Comment by ritma001** [comment]
Dear Ian,

It is indeed the case. So, I am supposed to use the narrowpeak for further analysis. Thank you a lot.

**Comment by IanCodes** [comment]
I use the narrowPeak file to display the binding regions on the UCSC
browser.  However, the majority of the information you need for downstream
analysis is in the .xls file.  It gives you the binding region coordinate,
the summit, the fold enrichment of the IP above the genomic background,,
plus P and q values.  I usually edit the file to create a "summit region"
of 200bp centred upon each summit, I find it useful for motif analysis.  I
also sort the file by fold enrichment, favouring those with a high value.
