### ISSUE TITLE
No model.r files generated

### ISSUE THREAD

**Issue by BisonKok** [taoliu/MACS#251]
Hi. I ran execute MACS2 as below:
`macs2 callpeak -t ChIP.input1.bam ChIP.input2.bam ChIP.input3.bam -c Control.input1.bam Control.input2.bam -f BAM -g hs  --nomodel --extsize 147 -n output.macs
`
I have the following outputs:
```
output.macs_peaks.narrowPeak
output.macs_peaks.xls
output.macs_summits.bed
```
I realize that there is supposed to be model.r output as well but it is missing. Any idea how I could generate this file? The version of MACS2 is 2.1.2_dev. Thanks.

**Comment by kernco** [comment]
It didn't generate a model.r file because you use the '--nomodel' parameter...so it didn't create a model. The model.r is for generating a graph showing the analysis macs2 does to determine the predominant fragment size, but your command skips this and just tells macs2 to extend your reads to a fragment size of length 147.

**Comment by taoliu** [comment]
@kernco is right :)

**Comment by anhong11** [comment]
I tried a cmd without --nomodel as:
macs2 callpeak -t ip.bam -c input.bam -f BAMPE --outdir ./macs_model -n IPvsInput -g 27977 -s 150

I did not get the model.r file as well. Do you know why?

**Comment by sufyazi** [comment]
I am here to report that using MACS/2.1.2.1-intel-2017.u2-Python-2.7.13 (installed on a cloud computing), still doesn't produce an .R file. I never used the --nomodel option. 

Here's the script I used:

`macs2 callpeak -t HA_BDP2_aligned_sorted.bam -c IN_BDP2_aligned_sorted.bam -f BAMPE -g 2.3e7 -n BDP2 --outdir /home/sufyazi/working_dir/macs2/BDP2-withmodel-qval-0p01 -q 0.01 -B`

Not sure why and I have reread the manual a few times to check if I'm missing something.

**Comment by taoliu** [comment]
@anhong11 With `-f BAMPE`, MACS will use paired-end mode to analyze the data. The model-building step will be skipped since the 'real' fragment size inferred from the mapped paried-ends will be used.
