### ISSUE TITLE
Segment fault issue

### ISSUE THREAD

**Issue by Swadha22** [taoliu/MACS#261]
Hi Tao,

I am having some issues with peak calling. From the terminal output, I can see that "building peak model" is being skipped and I guess that is why the peaks are not called. How do I fix this problem? 

The terminal output is pasted below.
Thanks in advance
Swadha

# Command line: callpeak -t /home/roylab/swadha/histone/HTZ_1/HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001.sam -n /HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001 -g ce --bdg --keep-dup=auto --broad --broad-cutoff=0.01 --nomodel -f SAM --extsize=250 --outdir /home/roylab/swadha/histone/HTZ_1/macs_output
# ARGUMENTS LIST:
# name = /HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001
# format = SAM
# ChIP-seq file = ['/home/roylab/swadha/histone/HTZ_1/HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001.sam']
# control file = None
# effective genome size = 9.00e+07
# band width = 300
# model fold = [5, 50]
# qvalue cutoff for narrow/strong regions = 5.00e-02
# qvalue cutoff for broad/weak regions = 1.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is on
# Paired-End mode is off

INFO  @ Wed, 03 Oct 2018 14:00:28: #1 read tag files...
INFO  @ Wed, 03 Oct 2018 14:00:28: #1 read treatment tags...
INFO  @ Wed, 03 Oct 2018 14:00:35:  1000000
INFO  @ Wed, 03 Oct 2018 14:00:41:  2000000
INFO  @ Wed, 03 Oct 2018 14:00:55: #1 tag size is determined as 50 bps
INFO  @ Wed, 03 Oct 2018 14:00:55: #1 tag size = 50
INFO  @ Wed, 03 Oct 2018 14:00:55: #1  total tags in treatment: 3353652
INFO  @ Wed, 03 Oct 2018 14:00:55: #1 calculate max duplicate tags in single position based on binomial distribution...
INFO  @ Wed, 03 Oct 2018 14:00:55: #1  max_dup_tags based on binomial = 2
INFO  @ Wed, 03 Oct 2018 14:00:55: #1 filter out redundant tags at the same location and the same strand by allowing at most 2 tag(s)
INFO  @ Wed, 03 Oct 2018 14:00:55: #1  tags after filtering in treatment: 2967172
INFO  @ Wed, 03 Oct 2018 14:00:55: #1  Redundant rate of treatment: 0.12
INFO  @ Wed, 03 Oct 2018 14:00:55: #1 finished!
INFO  @ Wed, 03 Oct 2018 14:00:55: #2 Build Peak Model...
INFO  @ Wed, 03 Oct 2018 14:00:55: #2 Skipped...
INFO  @ Wed, 03 Oct 2018 14:00:55: #2 Use 250 as fragment length
INFO  @ Wed, 03 Oct 2018 14:00:55: #3 Call peaks...
INFO  @ Wed, 03 Oct 2018 14:00:55: #3 Call broad peaks with given level1 -log10qvalue cutoff and level2: 1.301030, 2.000000...
INFO  @ Wed, 03 Oct 2018 14:00:55: #3 Pre-compute pvalue-qvalue table...
INFO  @ Wed, 03 Oct 2018 14:01:05: #3 In the peak calling step, the following will be performed simultaneously:
INFO  @ Wed, 03 Oct 2018 14:01:05: #3   Write bedGraph files for treatment pileup (after scaling if necessary)... /HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001_treat_pileup.bdg
INFO  @ Wed, 03 Oct 2018 14:01:05: #3   Write bedGraph files for control lambda (after scaling if necessary)... /HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001_control_lambda.bdg
INFO  @ Wed, 03 Oct 2018 14:01:05: #3 Call peaks for each chromosome...
Segmentation fault

**Comment by taoliu** [comment]
Could you remove the first '/' from the name "-n /HTZ1.SSTT004_S36HTZ1EX39_TTAGGC_L005_R1_001" and try again? Also, could you let me know the version of MACS2 you installed?

**Comment by Swadha22** [comment]
Hi Tao,

Thank you so much for your response. It works now. I have one more doubt which I wanted to clarify:

In my analysis, I didn't give any control/input SAM file then why am I getting "control_lambda.bdg" as one of the outputs which is: bedGraph format for input sample. How is this output generated?

Thanks in advance,
Swadha

**Comment by taoliu** [comment]
@Swadha22 When control data is not available, the control_lambda.bdg would be calculated from treatment/ChIP file instead of control/input in your case.
