### ISSUE TITLE
score from NarrowPeak >1000 when option --keep-dup all used

### ISSUE THREAD

**Issue by dianeking0** [taoliu/MACS#268]
Hi Tao,

I'm trying to use ENCODE-DCC/atac-seq-pipeline on my yeast data.  The pipeline calls MACS2 in the following way:

>macs2 callpeak -t $ATACPATH/ATAC_399_1_S19_L003_R1_001.trim.merged.nodup.tn5.tagAlign.gz -f BED -n ATAC_399_1_S19_L003_R1_001.trim.merged.nodup.tn5 -g 12631379 -p 0.01 --shift -37 --extsize 73 --nomodel -B --SPMR --keep-dup all --call-summits

MACS2 completes successfully but the pipeline fails soon after because it encountered a score from the 
narrowPeak file which is >1000.  (Since the documentation says the range is [0-1000], this is a error.)

>cat ATAC_399_1_S19_L003_R1_001.trim.merged.nodup.tn5_peaks.narrowPeak | awk -F'\t' '{print $5}' | awk '{if(min==""){min=max=$1}; if($1>max) {max=$1}; if($1<min) {min=$1}; total+=$1; count+=1} END {print "avg", total/count, "max", max, "min", min}'
>avg 628.772 max 19684 min 20

While swapping out various options to the macs2 callpeaks command, I discovered that the problem goes away if I remove the option --keep-dup all. 

>macs2 callpeak -t $ATACPATH/ATAC_399_1_S19_L003_R1_001.trim.merged.nodup.tn5.tagAlign.gz -f BED -n ATAC_399_1_S19_L003_R1_001.trim.merged.nodup.tn5 -g 12631379 -p 0.01 --shift -37 --extsize 73 --nomodel -B --SPMR  --call-summits

>cat ATAC_399_1_S19_L003_R1_001.trim.merged.nodup.tn5_peaks.narrowPeak | awk -F'\t' '{print $5}' | awk '{if(min==""){min=max=$1}; if($1>max) {max=$1}; if($1<min) {min=$1}; total+=$1; count+=1} END {print "avg", total/count, "max", max, "min", min}'
>avg 138.853 max 919 min 20

I'm not sure if I misunderstand what keep-dup does or if there is a problem with keep-dup

**Comment by taoliu** [comment]
When more reads are considered through `--keep-dup all`, the p-value will become more significant -- p-value large sample issue and the score will increase. The following text has been added to README.md:

> 5th: integer score for display. It's calculated as int(-10*log10pvalue) or int(-10*log10qvalue) depending on whether -p (pvalue) or -q (qvalue) is used as score cutoff. Please note that currently this value might be out of the [0-1000] range defined in UCSC ENCODE narrowPeak format. You can let the value saturated at 1000 (i.e. p/q-value = 10^-100) by using the following 1-liner awk: awk -v OFS="\t" '{$5=$5>1000?1000:$5} {print}' NAME_peaks.narrowPeak
