### ISSUE TITLE
Effective genome size for HG38?

### ISSUE THREAD

**Issue by ankush0128** [taoliu/MACS#270]
What is the effective genome size for files aligned to HG38?  Mappable genome size for default option hs is similar, if not, how much is the difference?

**Comment by dawe** [comment]
Check this page https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
In principle you should set 2.9e9 for hg38 and 2.8e9 for hg19, I suspect 2.7e9 has been calculated back in hg18 times. I don't feel it may change results a lot

**Comment by huanhuantai** [comment]
Hi, I work with a no-model plant species Aquilegia coerulea, the genome size of which is approximately 306.5Mb ( https://phytozome.jgi.doe.gov/pz/portal.html#!info?alias=Org_Acoerulea ), may I ask how to calculate its effective genome size?
 Many thanks!

**Comment by dawe** [comment]
In principle just count the number of non “N” character in the genome fasta file (that is, the number of bases that could be really mapped in an alignment). You can use the faSize tool from Jim Kent (UCSC tools) or some bash one-liner

**Comment by huanhuantai** [comment]
Many thanks!
kind regards, Huanhuan

**Comment by taoliu** [comment]
Thank you Davide @dawe for answering the question!
