### ISSUE TITLE
Feat: Update documentation

### ISSUE THREAD

**Issue by ATpoint** [taoliu/MACS#284]
I suggest updating the documentation to include the relatively new `--min-length` paramater. We just had a [question on Biostars](https://www.biostars.org/p/372577/) towards filtering for minimal peak width which is why I noticed that it is missing from the README here on Git.

**Comment by taoliu** [comment]
Thanks! Just added the description for --`min-length` and `--max-gap`: a53fd20

**Comment by taoliu** [comment]
Changes have been integrated into `master` branch and will be included in the next release.
