### ISSUE TITLE
Q: Issue install MACS2 - Python 2.7, Pip version deprecating

### ISSUE THREAD

**Issue by ankush0128** [taoliu/MACS#287]
Installing MACS2 with Pip3 

> pip3 install MACS2
> Collecting MACS2
>   Using cached https://files.pythonhosted.org/packages/5e/32/0108a85d9a91c18413e8492bea631725cdbc20b45970ef63e8d0020ef2da/MACS2-2.1.2.1.tar.gz
>     ERROR: Complete output from command python setup.py egg_info:
>     ERROR: CRITICAL: Python version must be 2.7!
>     ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6h3j14wy/MACS2/

**Installing MACS2 with Python version 2.7 and pip **
Python 2.7 version will be deprecating in 2020 and Pip will drop support for Python 2.7

Error message on install: 

> Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Collecting numpy
>   Downloading https://files.pythonhosted.org/packages/e1/72/179a78b565ecf01fe98dab6417581d30acac15c2d93c49f93169ebea99b1/numpy-1.16.3-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
>      |################################| 17.0MB 4.9MB/s 
> ERROR: pymatgen 3.3.1 requires enum34, which is not installed.
> ERROR: pymatgen 3.3.1 requires scipy>=0.14, which is not installed.
> ERROR: pandas 0.17.1 requires python-dateutil, which is not installed.
> ERROR: pandas 0.17.1 requires pytz>=2011k, which is not installed.
> ERROR: matplotlib 1.5.1 requires pyparsing!=2.0.4,>=1.5.6, which is not installed.
> ERROR: matplotlib 1.5.1 requires python-dateutil, which is not installed.
> ERROR: matplotlib 1.5.1 requires pytz, which is not installed.

How to rectify these error messages and successfully install MACS2 updated version 

Thanks in advance 
Best Regards 
Ankush

**Comment by whositwhatnow** [comment]
You are using python 3.  MACS2 is not compatible with python3, it must be python2.7

**Comment by taoliu** [comment]
Refer to #242
