### ISSUE TITLE
Q: Generating wiggle file from bam 

### ISSUE THREAD

**Issue by aperreault** [taoliu/MACS#290]
Hey there!

I have a Tophat aligned RNA-seq BAM file and I'd like to generate a wiggle or bedGraph file for visualization. Can I do this with MACS2? If so, which command would I use and can I use the bam input without running MACS2 to "call peaks" on my RNA-seq file?

Thanks!
-Andrea

**Comment by MahShaaban** [comment]
The MACS2 subcommand to generate bedGraph (signal track) is `bdgcmp` which uses the output files of the peak call!
Why not use [bamCoverage](https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html)?

**Comment by taoliu** [comment]
@aperreault You can use "macs2 pileup" command.
