### ISSUE TITLE
Q: bdgcmp without normalizing for sequencing depth?

### ISSUE THREAD

**Issue by smarhon** [taoliu/MACS#296]
Is it possible to add an option to bdgcmp command for not to normalize the target and control bedgraphs to sequencing depth? Assuming that they have already been normalized in a particular way before runing this command.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by taoliu** [comment]
@smarhon bdgcmp won't normalize values in bedGraph files unless you set -S option. The assumption in bdgcmp is that users have already normalized the data by themselves.

**Comment by smarhon** [comment]
Thank you for this clarification!

Best
Sajid

**Comment by taoliu** [comment]
You are welcome!
