### ISSUE TITLE
Q: NAME_treat_pvalue.bdg not generated even though --bdg is set

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [taoliu/MACS#297]
I want to use the macs2 cmbreps option to compare peaks between replicates. However I can not seem to produce the log10 pvalues.
When I call macs2 (v2.1.2) with the --bdg command I get the NAME_treat_pileup.bdg and the NAME_control_lambda.bdg as described [here](https://github.com/taoliu/MACS/blob/master/README.md#-b--bdg), however I do not get NAME_treat_pvalue.bdg or NAME_treat_qvalue.bdg.

The header of the NAME_peaks.xls is:

\# This file is generated by MACS version 2.1.2
\# Command line: callpeak --bdg -t /mnt/ocimum/vol/atacpipeline/dedup/GSM2837484-Bl71nemr.bam --outdir /mnt/ocimum/vol/atacpipeline/macs2/ -n GSM2837484-Bl71nemr --shift -100 --extsize 200 --nomodel --keep-dup 1 --buffer-size 10000 -g 415501436
\# ARGUMENTS LIST:
\# name = GSM2837484-Bl71nemr
\# format = AUTO
\# ChIP-seq file = ['/mnt/ocimum/vol/atacpipeline/dedup/GSM2837484-Bl71nemr.bam']
\# control file = None
\# effective genome size = 4.16e+08
\# band width = 300
\# model fold = [5, 50]
\# qvalue cutoff = 5.00e-02
\# The maximum gap between significant sites is assigned as the read length/tag size.
\# The minimum length of peaks is assigned as the predicted fragment length "d".
\# Larger dataset will be scaled towards smaller dataset.
\# Range for calculating regional lambda is: 10000 bps
\# Broad region calling is off
\# Paired-End mode is off
\# tag size is determined as 43 bps
\# total tags in treatment: 28550699
\# tags after filtering in treatment: 20545115
\# maximum duplicate tags at the same position in treatment = 1
\# Redundant rate in treatment: 0.28
\# Sequencing ends will be shifted towards 5' by 100 bp(s)
\# d = 200

**Comment by Maarten-vd-Sande** [comment]
The files are never even generated, see funcion `__write_bedGraph_for_a_chromosome` and for instance here:
https://github.com/taoliu/MACS/blob/b1c77ee1d18f00ed33fbdea2a1f14bea349918c7/MACS2/IO/CallPeakUnit.pyx#L1482

How do I get those files anyway?

**Comment by taoliu** [comment]
@Maarten-vd-Sande MACS2 main function "callpeak" only generates bedGraph for pileup signals. To make pvalue bedGraph, please use "bdgcmp" command, in the same way as shown, except that you specify the method as ppois "-m ppois": 

https://github.com/taoliu/MACS/wiki/Build-Signal-Track#Run_MACS2_bdgcmp_to_generate_foldenrichment_and_logLR_track

**Comment by Maarten-vd-Sande** [comment]
That seems to work, thanks a lot! Maybe update the documentation since it's quite misleading.

**Comment by taoliu** [comment]
@Maarten-vd-Sande Sure thing! I just updated the README file: 8ebd97b1730b7aca4a06d6ec4427ccd0dc14cf6a
