### ISSUE TITLE
Q: How to calculate fold-enrichment or -log10(pvalue) for given peaks 

### ISSUE THREAD

**Issue by 674040463** [taoliu/MACS#332]
I want to know when I use macs2 callpeak to analysis TF1 chip-seq and get TF1 peaks and then I want to calculate fold-enrichment or -log10(pvalue) for TF1 peaks in TF2 or TF3 chip-seq, what could I do. Thank you so much for taking the time reading this question

**Comment by yue131** [comment]
First use bamcoverage to calculate the number of counts in given peaks, then use DESeq to investigate the different peaks.

**Comment by 674040463** [comment]
> First use bamcoverage to calculate the number of counts in given peaks, then use DESeq to investigate the different peaks.

OK. Thank you for your reply. Your reply helps me a lot and solve this problem
