### ISSUE TITLE
Bug: macs2 docker container v2.2.5 installs v2.1.3 of macs2

### ISSUE THREAD

**Issue by tinavisnovska** [taoliu/MACS#346]
hi,

when I run `macs2 --version` from inside the macs2 container, I get v2.1.3 even though the documentation in https://github.com/taoliu/MACS/tree/master/DOCKER says that there is v2.2.5 inside the container. 

best.

**Comment by taoliu** [comment]
I didn't set up automatic deployment to Dockerhub. That's why the docker image there is still old. Please check the macs2 docker image from bioconda:

https://bioconda.github.io/recipes/macs2/README.html
https://quay.io/repository/biocontainers/macs2?tab=tags

**Comment by tinavisnovska** [comment]
thanks for the info!
