### ISSUE TITLE
Bug: bdgbroadcall reporting problem

### ISSUE THREAD

**Issue by Me6me82** [taoliu/MACS#362]
**Describe the bug**
I’m trying to call peaks using bdgbroadcall from bdg generates by cmbreps and -m fisher  But the out put of the bdgbroadcall contain no p – value or any other than coordinate (below you can find the heading of the output)

track name="peak" description="peak" type=gappedPeak nextItemButton=on

chr1 818930 819140 H3K4me1_H0_1_2_G840.bdg_broadRegion1 0 . 818930 819140 0 2 1,1 0,209 0.00000 0.00000 0.00000

chr1 903599 904278 H3K4me1_H0_1_2_G840.bdg_broadRegion2 0 . 903599 904278 0 3 1,632,1 0,37,678 0.00000 0.00000 0.00000

chr1 905126 907304 H3K4me1_H0_1_2_G840.bdg_broadRegion3 0 . 905126 907304 0 3 1,212,1 0,1915,2177 0.00000 0.00000 0.0000

**To Reproduce**

So this what I did

1 call peaks after removing all duplicates
macs2 callpeak -t $INDIR/ Sample1_Mkdup_fliter.bam \
-c $Input/Input_Mkdup_fliter.bam \
-f BAM -g hs -n H3K4me1_H0_1 -B --broad -q 0.01 --keep-dup all --nomodel --extsize 210 –outdir

2 compare pileup and lambda for each replicates to get pvalue track
macs2 bdgcmp -t rep1_pileup.bdg -c rep1_lambda.bdg -m ppois -o rep1_pvalue.bdg
macs2 bdgcmp -t rep2_pileup.bdg -c rep2_lambda.bdg -m ppois -o rep2_pvalue.bdg

3- combine both files
macs2 cmbreps -i rep1_pvalue.bdg rep2_pvalue.bdg -m fisher -o rep1_rep2_pvalue.bdg.bdg

4 recall peaks
macs2 bdgbroadcall -i rep1_rep2_pvalue.bdg.bdg -c 8 -l 210 -g 76 -o rep1_rep2.bdg

**Expected behavior**
I think it is a reporting problem by macs2 , since the narrow peak calling with bdgpeakcall tool work fine

**Screenshots**
![image](https://user-images.githubusercontent.com/25483535/76671837-cdc69780-6598-11ea-93fc-311797a17af0.png)

**System (please complete the following information):**
 - OS: [e.g. Linux, Mac OSX]
 

**Additional context**

**Comment by Me6me82** [comment]
Hei
Do you have any update on the issue

**Comment by taoliu** [comment]
@Me6me82 I will fix that. The plan is to output the average score in the 5th column.

**Comment by Me6me82** [comment]
Thank you , yes

**Comment by Me6me82** [comment]
Hei
Do you have any update on the issue

**Comment by taoliu** [comment]
@Me6me82 I am currently working on other issues (359 and 351). Will work on this later...

**Comment by taoliu** [comment]
@Me6me82 Fixed in PR #373. Will be included in the next release.

**Comment by Me6me82** [comment]
@taoliu Thanks, when do you expect the next release will be available!

**Comment by taoliu** [comment]
@Me6me82 This week.

**Comment by taoliu** [comment]
@Me6me82 v2.2.7.1 is out.
