### ISSUE TITLE
using --ratio in macs2 callpeak to do spike-in normalization?

### ISSUE THREAD

**Issue by olechnwin** [taoliu/MACS#366]
Hi,

I noticed there is a similar question on how to incorporate spike-in normalization into macs2 peak calling in #356 which recommends doing subcommands. 
However, I saw that `macs2 callpeak` has `--ratio `option and am wondering whether this is a new feature that enable us to specify spike-in normalization via `--ratio` instead of doing the subcommands?

Thanks in advance!

**Comment by taoliu** [comment]
@olechnwin NO! Don't use that option. I checked the changelog and it was mentioned almost 6 years ago. In fact, this option is not effective in any of the current versions of MACS2. I will make sure it is removed in the next release!

**Comment by olechnwin** [comment]
@taoliu 
Thank you so much for the reply!! Really appreciate it!

**Comment by taoliu** [comment]
`--ratio` has been removed in the MACS2 code. The change will be included in the next release v2.2.7.
