### ISSUE TITLE
Q: Combine --qvalue with bdgpeakcall 

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [taoliu/MACS#368]
**Use case**
I used cmbreps to combine replicates and now i want to call peaks on this, however I don't see how I can change the qvalue.

**Describe the problem**
I want to change the qvalue

**Comment by taoliu** [comment]
Currently, there is no subcommand that supports pvalue-qvalue conversion. I think I can implement one under `bdgopt` subcommand...

**Comment by Maarten-vd-Sande** [comment]
Is it possible to use `bdgpeakcall ` with a pvalue cutoff

**Comment by taoliu** [comment]
Of course, yes! `bdgpeakcall` applies cutoff on any type of score that the 4th column of the bedGraph file contains. If you used `cmbreps -m fisher`, then the 4th column of the output bedGraph file should be in '-log10 pvalue' format. So if you `bdgpeakcall -c 5` will apply pvalue `1e-5` as the cutoff.

**Comment by Maarten-vd-Sande** [comment]
Great thanks!
