### ISSUE TITLE
Q: peaks extended outside of chromosome

### ISSUE THREAD

**Issue by TheSallyGardens** [taoliu/MACS#371]
Hi,@taoliu .
When I use macs2 call peaks,I get a peak extended outside of chromosome.
![深度截图_选择区域_20200331144255](https://user-images.githubusercontent.com/40382381/77995385-4631a480-735e-11ea-9662-25d3ac01ee98.png)

Align:BWA  Ref:Hg19

Hg19's chr17  is only 81195210.
81195249 > 81195210
Looking forward to your reply!

**Comment by TheSallyGardens** [comment]
CMD:macs2 callpeak -t test.bam -n test -g hs --outdir Cluster_peaks --nomodel --shift 100 --ext 200 --qval 1e-2 -B --SPMR --tempdir ./tmp

**Comment by taoliu** [comment]
@TheSallyGardens It's possible that `--shift 100 --ext 200` will move out of chromosome boundary. Because MACS2 doesn't check this. You can use `bedClip` from UCSC toolkit to clip the those off-boundary peaks out.

https://anaconda.org/bioconda/ucsc-bedclip

**Comment by TheSallyGardens** [comment]
Thank you!

**Comment by taoliu** [comment]
You are welcome! The issue is closed.
