### ISSUE TITLE
Q: MACS2 IndexError: list index out of range #652

### ISSUE THREAD

**Issue by zoucheng123** [taoliu/MACS#374]
I get the following error stack upon running callpeak on my two SAM-files (from bowtie). 
Any way I can troubleshoot what is wrong here?
Thank you so much!

# Command line: callpeak -t ip.sam -c input.sam --name=m6A --format=SAM --tsize=36 --nomodel --extsize=100
# ARGUMENTS LIST:
# name = m6A
# format = SAM
# ChIP-seq file = ['ip.sam']
# control file = ['input.sam']
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Tue, 07 Apr 2020 23:04:37: #1 read tag files... 
INFO  @ Tue, 07 Apr 2020 23:04:37: #1 read treatment tags... 
Traceback (most recent call last):
  File "/public/software/anaconda3/bin/macs2", line 652, in <module>
    main()
  File "/public/software/anaconda3/bin/macs2", line 51, in main
    run( args )
  File "/public/software/anaconda3/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 65, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/public/software/anaconda3/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 391, in load_tag_files_options
    treat = tp.build_fwtrack()
  File "MACS2/IO/Parser.pyx", line 188, in MACS2.IO.Parser.GenericParser.build_fwtrack
  File "MACS2/IO/Parser.pyx", line 203, in MACS2.IO.Parser.GenericParser.build_fwtrack
  File "MACS2/IO/Parser.pyx", line 783, in MACS2.IO.Parser.SAMParser.__fw_parse_line
IndexError: list index out of range

**Comment by taoliu** [comment]
@zoucheng123 Thanks for reporting the issue! Could you share with me the version number? Also, since SAM is plain text format, I am not sure if the file is corrupted. Try to convert it to BAM format and try to see if there is any issue during the conversion. Then try to feed the BAM files to macs2.

**Comment by zoucheng123** [comment]
Thanks for your help.
I use macs2 2.2.6 to analysis m6A  dataset. The SAM file is corrupted, as you say,  in that there are lots of errors when I try to convert it to BAM file. Fortunately, when I get SAM file by bwa instead of bowtie, macs2 works well and I get three result files (m6A_peaks.narrowPeak, m6A_peaks.xls, m6A_summits.bed). Thanks again!

**Comment by taoliu** [comment]
You are welcome!

**Comment by medsimo** [comment]
Guys, we are instaling some MACS3 modules in our Machines, we had Error A04. What that means. have you guys some Error list? 
thank you in advance! 
Simo
