### ISSUE TITLE
Q: p-value of peak in MACS2

### ISSUE THREAD

**Issue by taeyoungh** [taoliu/MACS#376]
Hi, I am wondering how MACS2 calculate p-value for identified peak. As far as I am understood, MACS2 performs poisson test base-by-base across genome and does multiple test correction, resulting in q-values. Peaks are constructed from the regions above the threshold of q-value/fold change. Am I correct? Then, my question is how to calculate a p-value/q-value for a peak if p-values/q-values are calculated base-by-base.

**Comment by taoliu** [comment]
@taeyoungh Thanks for asking! Yes, you are right. In MACS2, the peak level p/q-value (in terms of narrowPeak) is the p/q-value at the summit of the peak, or in another word, the best p/q-value within the peak. For broadpeak mode, it's the average p/q-value in the peak region.

**Comment by taeyoungh** [comment]
Thank you for clarifying it for me !!

**Comment by taoliu** [comment]
You are welcome! @taeyoungh
