### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by mb6434** [taoliu/MACS#377]
Dear Taoliu,

I am using macs2 2.1.2 version and working with BAMPE file. When I am looking at the manual (macs2 -h), I could see that the following arguments are available: --min-length, --max-gap. However when I tried tu use it, I get the following message: 'macs2: error: unrecognized arguments: --min-length 500 --max-gap 5000'. 

Combined to them I used the following arguments: 
--format BAMPE \
--gsize 1.87e9 \
--outdir  \
--name  \
--outdir  \
--bdg \
--qvalue 0.05 \
--broad \
--cutoff-analysis \
--fe-cutoff 1.0 \

Please, would you like to tell me what is the issue? 

Thank you very much for your help,

MB

**Comment by taoliu** [comment]
@mb6434 I believe you saw the help information through `macs2 callpeak -h` command instead of `macs2 -h`. You need to use `macs2 callpeak` to access the above options.

**Comment by mb6434** [comment]
Thank you for your answer. I used macs2 callpeak command combined with those arguments as follow:
macs2 callpeak -t treatment.bam \
-c control.bam \
--format BAMPE \
--gsize 1.87e9 \
--name macs2_test1 \
--outdir peakcall/macs2/ \
--bdg \
--qvalue 0.05 \
--min-length 500 \
--max-gap 5000 \
--broad \
--cutoff-analysis \
--fe-cutoff 1.0 \


Do you think that if I upload the last version of macs2 this would overcome the issue?

Thank you very much for your help

**Comment by taoliu** [comment]
@mb6434 Definitely, please update to the most recent macs2. The v2.1.2 is 4 years old. But I am sure the `--max-gap` and `--min-length` options are valid in v2.1.2. There is a possibility that you have multiple MACS2 installations in the same environment and they are messed up. You'd better use either `virtualenv` or `conda` to manage your tools under isolated environments -- not only the python tools like MACS2.

**Comment by mb6434** [comment]
I do not know how is it install as I am runnind macs2 on a cluster. Many thanks for your advises.

**Comment by taoliu** [comment]
@mb6434 You are welcome! Please use virtualenv (https://docs.python.org/3/library/venv.html) or conda (https://docs.conda.io/en/latest/miniconda.html)  on the cluster, and that will make your life much much easier :)

**Comment by mb6434** [comment]
Yep, I installed conda one month ago in my own computer. I will see now for the cluster. Thank you very much.
