### ISSUE TITLE
Bug: bdgpeakcall output zeros

### ISSUE THREAD

**Issue by olechnwin** [taoliu/MACS#379]
**Describe the bug**
This is very similar to #362 in that using `bdgpeakcall` generates output that contain zeros in columns 7-9.
  
Below, example lines from bdgpeakcall output file
```
track type=narrowPeak name="peaks.bed" description="peaks.bed" nextItemButton=on
chr1	12237	15856	peaks.bed_narrowPeak1	367	.	0.00000	0.00000	0.00000	905
chr1	16017	16585	peaks.bed_narrowPeak2	90	.	0.00000	0.00000	0.00000	425
chr1	16786	18924	pval_peaks.bed_narrowPeak3	218	.	0.00000	0.00000	0.00000	704
```

**To Reproduce**
I am following the steps in [https://github.com/taoliu/MACS/wiki/Advanced%3A-Call-peaks-using-MACS2-subcommands]() . 
At the last step to call peaks on score track using a cutoff, this what I did:
`macs2 bdgpeakcall -i peak_pvalue.bdg -c 2 -l 175 -g 150 -o peaks.bed
`

**Expected behavior**
I can see peak_pvalue.bdg have pvalues that are not zero
Here are the first few  peaks in peak_pvalue.bdg sort by 5th column (i.e. -log10(pvalue))

```
 sort -nrk 4 peaks_pvalue.bdg | head
chr3    122870739       122870740       2952.45776
chr3    122870740       122870742       2940.46948
chr3    122870742       122870743       2935.67627
```

Here are the first few sorted peaks based on 8th column which should be -log10(pvalue)
```
sort -nrk 8 peaks.bed | head -n 10
track type=narrowPeak name="peaks.bed" description="peaks.bed" nextItemButton=on
chrY    959237  959448  peaks.bed_narrowPeak212237     68      .       0.00000 0.00000 0.00000 166
chrY    7717573 7717766 peaks.bed_narrowPeak212349     83      .       0.00000 0.00000 0.00000 45
chrY    7311337 7311645 peaks.bed_narrowPeak212348     631     .       0.00000 0.00000 0.00000 230
```

Here are the  same narrowpeak file but sorted based on 5th column
```
sort -nrk 5 peaks.bed | head -n 10
chr3    122867452       122877691       peaks.bed_narrowPeak151954     29524   .       0.00000 0.00000 0.00000 3287
chr12   72773195        72777012        peaks.bed_narrowPeak48999      25339   .       0.00000 0.00000 0.00000 1398
chr15   90017533        90024659        peaks.bed_narrowPeak68747      24055   .       0.00000 0.00000 0.00000 506
```
 
**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - MACS Version  2.2.6 and 2.1.4

**Additional context**
I first discovered the problem running macs version 2.1.4. Since #362 mentioned narrow peak calling with `bdgpeakcall` works fine, I upgraded to macs version 2.2.6 and had the same problem.

Thank you!

**Comment by taoliu** [comment]
@olechnwin It's impossible to let bdgpeakcall to output the last three columns. This tool is a straightforward simple peak calling tool which will check the 4th column in bedGraph file and call the regions above a given cutoff. Nothing else. It has NO idea of what type of value in the 4th column of bedGraph file. In the output of bdgpeakcall, the 5th column is related to the score in peak summit from bedGraph.  The 5th column score = 10 * score in the summit from bedGraph.

**Comment by olechnwin** [comment]
Ahhh....Thank you very much for your quick response. In the subcommand tutorial, it mentioned that the output is a narrowpeak file so I assumed it should have all the values as in narrowpeak file.
Sorry about that.

**Comment by taoliu** [comment]
@olechnwin You are welcome! I will revise my tutorials.

**Comment by olechnwin** [comment]
@taoliu, Nah. Your tutorial is correct. It stated that the output is in narrowpeak format. I just need to learn how to read properly :-)
I just have to mention how grateful I am with the support you provided. It is also amazing how you do this by yourself!
