### ISSUE TITLE
Q: The Broad peak calling with extra parameter --nomodel  --extsize 73 gives biologically opposite result compared to default broad peaks calling

### ISSUE THREAD

**Issue by AnnaKuchmiy** [taoliu/MACS#382]
Dear MACS2 programmers, 
We are analyzing ChiPmentation data of H3K27m3 mark, data was generated in our lab. It happened, that we used 2 different approaches to call peaks:
1st approach: macs2 callpeak -t Sample.bam -c Control.bam -f BAM -g hs -B --broad -n  --outdir ~/H3K27me 
2nd approach: macs2 callpeak -t Sample.bam -c Control.bam -f BAM -g hs -B --broad -n  --outdir ~/H3K27me **--nomodel  --extsize 73**

The problem is, that the resulting broad peaks from the same sample, but different approaches, differs dramatically. Where second approach shows general loss of H4K27me3, the first approach demonstrates the gain of this mark. 
We also checked the control genes H4K27me3 status but with 2 different packages, DeSeq2 and DiffBind (using DeSeq2 algorithm). And the control genes demonstrate expected pattern with approach 1 and approach 2. 

I plotted pileups from the different approaches: 
![ready_forum](https://user-images.githubusercontent.com/15571241/79689882-ee4cd600-8257-11ea-80ac-b85cda6caf50.jpeg)

Is this analysis already enough to conclude that 1 approach is better? 

What would be the best way to decide which peak calling line is better? Are there any possible additional analysis of the peak lists to select the way?

Many thanks in advance,
Best wishes, 
Anna

**Comment by taoliu** [comment]
Hi @AnnaKuchmiy! The first question: is your data paired-end or single-end? I remember the first ChIPmentation data is paired-end. If PE, then please use `macs2 callpeak -t Sample.bam -c Control.bam -f BAMPE -g hs -B --broad -n --outdir ~/H3K27me` instead. Alternatively, you can keep using the same parameter settings as in the first ChIPmentation paper with `--nomodel --extension 75` uniformly on all your data.

In general, if you plan to compare different conditions, please avoid the 'read shift model prediction' (the default behavior **without** setting `--no-model`) in MACS2 as that in your approach 1. It's highly likely that the 'extension sizes' from the two conditions predicted by MACS2 are different so the data are smoothed differently. For example, if you have the identical dataset, and you try to set the extension size to 100, and then set as 200, the later one will double the overall genome-wide pileup signals, so give you misleading results. 

Now, I am thinking of turning the 'model building' off by default. This feature currently is often used to evaluate the data quality ONLY.

**Comment by AnnaKuchmiy** [comment]
Thank you, @taoliu ! Very clear answer!
