### ISSUE TITLE
Q: Too few paired peaks (0) so I can not build the model! Broader you r MFOLD range parameter may erase this error.

### ISSUE THREAD

**Issue by Rya-Stark** [taoliu/MACS#390]
Hi,

I get this error while peak calling when not using a control.I get peaks when i use control. Why is this ?

Command:
macs2 callpeak -t Treated_Q30Filtered.rmdup.bam -f BAM -g 4432532 -B -n Treated

Error:
"WARNING @ Sun, 10 May 2020 11:10:32: Too few paired peaks (0) so I can not build the model! Broader your MFOLD range parameter may erase this error. If it still can't build the model, we suggest to use --nomodel and --extsize 147 or other fixed number instead.
WARNING @ Sun, 10 May 2020 11:10:32: Process for pairing-model is terminated!"

Even if i change the parameters ( I have changed MFOLD, --nomodel ,  --extsize and q value),  the program runs but with no peaks.

Why is it so?

**Comment by taoliu** [comment]
@Rya-Stark By default, MACS will pre-scan the data to identify some enriched regions then build a model to estimate fragment size. If there are few regions ( in your case, 0), you will see this error. You can use `--nomodel` to skip the model building, and specify `--extsize` with a reasonable number such as 200. With `--nomodel --extsize 200`, you shouldn't see such error again.

Another suggestion, it seems you are working on a small genome which means the sequencing depth may be too high, check this thread #353 to see if it helps: https://github.com/taoliu/MACS/issues/353

**Comment by Rya-Stark** [comment]
Thank you so much.  --nomodel --extsize 200 still didnt work for me, but Thread #353 explains it.
