### ISSUE TITLE
"ZeroDivisionError: float division" from -f BAMPE option in callpeak

### ISSUE THREAD

**Issue by NBKingsley** [taoliu/MACS#392]
Hello! 

I am seeing the following error when I try to use MACS2 (2.2.7.1) to call peaks for PE data. 
```
# Command line: callpeak -t BWA_Output/Narrow/H3K27ac_Skin_A.duplicate-removed.bam -c BWA_Output/Duplicates/Input_Skin_A.duplicate-removed.bam -f BAMPE -n Peak_Calls/H3K27ac_Skin_A -g 2409143234
# ARGUMENTS LIST:
# name = Peak_Calls/H3K27ac_Skin_A
# format = BAMPE
# ChIP-seq file = ['BWA_Output/Narrow/H3K27ac_Skin_A.duplicate-removed.bam']
# control file = ['BWA_Output/Duplicates/Input_Skin_A.duplicate-removed.bam']
# effective genome size = 2.41e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is on
 
INFO  @ Thu, 14 May 2020 16:02:11: #1 read fragment files... 
INFO  @ Thu, 14 May 2020 16:02:11: #1 read treatment fragments... 
INFO  @ Thu, 14 May 2020 16:02:14: 0 fragments have been read. 
Traceback (most recent call last):
  File "/share/apps/bio3user/miniconda3/envs/macs2/bin/macs2", line 653, in <module>
    main()
  File "/share/apps/bio3user/miniconda3/envs/macs2/bin/macs2", line 51, in main
    run( args )
  File "/share/apps/bio3user/miniconda3/envs/macs2/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 64, in run
    if options.PE_MODE: (treat, control) = load_frag_files_options (options)
  File "/share/apps/bio3user/miniconda3/envs/macs2/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 350, in load_frag_files_options
    treat = tp.build_petrack()
  File "MACS2/IO/Parser.pyx", line 1267, in MACS2.IO.Parser.BAMPEParser.build_petrack
  File "MACS2/IO/Parser.pyx", line 1311, in MACS2.IO.Parser.BAMPEParser.build_petrack
ZeroDivisionError: float division
```

From some searching, I've noticed that a few other MACS2 commands gave a similar error (#383 and #386 ) due to a bug in the code. Is that possibly what is causing this error message too?

Here is the head of one of my bam files from my treatment group in case it provides any helpful information:

@HD	VN:1.5	SO:coordinate
@SQ	SN:chr1	LN:188260577
@SQ	SN:chr2	LN:121350024
@SQ	SN:chr3	LN:121351753
@SQ	SN:chr4	LN:109462549
@SQ	SN:chr5	LN:96759418
@SQ	SN:chr6	LN:87230776
@SQ	SN:chr7	LN:100787686
@SQ	SN:chr8	LN:97563019
@SQ	SN:chr9	LN:85793548
@SQ	SN:chr10	LN:85155674
@SQ	SN:chr11	LN:61676917
@SQ	SN:chr12	LN:36992759
@SQ	SN:chr13	LN:43784481
@SQ	SN:chr14	LN:94600235
@SQ	SN:chr15	LN:92851403
@SQ	SN:chr16	LN:88962352
@SQ	SN:chr17	LN:80722430
@SQ	SN:chr18	LN:82641348
@SQ	SN:chr19	LN:62681739
@SQ	SN:chr20	LN:65343332
@SQ	SN:chr21	LN:58984458
@SQ	SN:chr22	LN:50928189
@SQ	SN:chr23	LN:55556184
@SQ	SN:chr24	LN:48288683
@SQ	SN:chr25	LN:40282968
@SQ	SN:chr26	LN:43147642
@SQ	SN:chr27	LN:40254690
@SQ	SN:chr28	LN:47348498
@SQ	SN:chr29	LN:34776120
@SQ	SN:chr30	LN:31395959
@SQ	SN:chr31	LN:26001039
@SQ	SN:chrX	LN:128206784
@PG	ID:bwa	PN:bwa	VN:0.7.9a-r786	CL:bwa mem -M -t 3 /home/nbk/FAANG_Project/Genome/EquCab3.0_Genbank_Build.nowrap.fasta Trimmed_Reads/H3K27ac_Skin_A_R1_val_1.fq.gz Trimmed_Reads/H3K27ac_Skin_A_R2_val_2.fq.gz
@PG	ID:MarkDuplicates	VN:2.8.1	CL:picard.sam.markduplicates.MarkDuplicates INPUT=[Sort/H3K27ac_Skin_A.sorted.bam] OUTPUT=Duplicates/H3K27ac_Skin_A.duplicate-marked.bam METRICS_FILE=Duplicates/H3K27ac_Skin_A.dup_metrics REMOVE_DUPLICATES=false ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json	PN:MarkDuplicates
A00902:80:HL7Y2DRXX:2:2147:17589:4930	161	chr1	677	60	49M	=	1254	626	ACCTAAGTATTTCAAGGTATTTTTGGTACTATTGAAAATCATATGCTTA	F:F,FFFFFFFFFF:FF:FFFF:,FFF,FFFFFFFFF:FFFF:FFFFFF	MD:Z:29G4G9T4	PG:Z:MarkDuplicates	NM:i:3	AS:i:34	XS:i:20
A00902:80:HL7Y2DRXX:2:2208:31412:24549	145	chr1	5276	60	2S47M	chr6	27664629	0	TTCATTTCTTAAAAGCAAAACATGCTGTCTTTCAATTCAGAAAGGCCGG	:FFFFFFFFFFF:FFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MD:Z:16C28A1	PG:Z:MarkDuplicates	NM:i:2	AS:i:40	XS:i:19
A00902:80:HL7Y2DRXX:2:2141:21206:6934	129	chr1	13335	60	47M	chr10	12337455	0	CAAGAGTGCAAGGAGCGAATTTCTTCCCTGAACTCCCAGATCGAGGA	FFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFFFFF	MD:Z:47	PG:Z:MarkDuplicates	NM:i:0	AS:i:47	XS:i:20
A00902:80:HL7Y2DRXX:2:2150:12228:2848	65	chr1	18596	60	50M	chr22	49184915	0	CAGGAAAGACGATAGTGTAAGTTCCAGGCTGAGGGCAGGAGAGGACCCAT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:20
A00902:80:HL7Y2DRXX:2:2208:6768:5134	97	chr1	18679	60	49M	chr30	26290956	0	GTCCTCTTCCTCAGCACTTCCGTTCTATTCAAATGTTCACTGATTGGAT	FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFF	MD:Z:49	PG:Z:MarkDuplicates	NM:i:0	AS:i:49	XS:i:21
A00902:80:HL7Y2DRXX:2:2173:15031:34507	161	chr1	36613	60	50M	=	37231	668	TGACAGACATTGGGAAAAAGAAGTCAAAGCCTAGATGACTGTTGCAGCTG	FFFF,FFFFFFFFF,FF,:FFFFFFF:FF:FFFFFFFFFFFF,FFFFF:F	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:21
A00902:80:HL7Y2DRXX:2:2173:15031:34507	81	chr1	37231	60	50M	=	36613	-668	AGGGGTGGAGATGAACAAGATAGTGCCCATTACTTCTCACTCTGCCGTGC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:19
A00902:80:HL7Y2DRXX:2:2258:5385:35368	161	chr1	46963	60	50M	chr10	17682362	0	CTTGCCTCCTAACCCTCACTTGACAACCACTGAAATTCTGGGTTGTTGTT	FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:19
A00902:80:HL7Y2DRXX:2:2261:11532:21120	145	chr1	47761	60	49M	=	79012	31204	GAGAGTTCAGAGTGCTGATGGTTTCTCATTGGCTGAGCTGCTGGGATAG	FFFFFFF,F:FF:FFFFF:FF,FFF:FF:FFF,FFF:FFF:F:FFFFFF	MD:Z:49	PG:Z:MarkDuplicates	NM:i:0	AS:i:49	XS:i:30
A00902:80:HL7Y2DRXX:2:2160:31367:22780	161	chr1	56106	60	50M	=	56643	587	ACCAGAAAGAGAGTCCTCACCTGAACCAAACTGGTCAGCGCCTTGATCTG	FFF:FFFF:,FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:19
A00902:80:HL7Y2DRXX:2:2160:31367:22780	81	chr1	56643	60	50M	=	56106	-587	CAAAGGACTCACTTCAGCTTTAAGGACACACCTATACAAACAGTCAAGGA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:29
A00902:80:HL7Y2DRXX:2:2117:21658:9909	65	chr1	75812	35	50M	chr3	19954790	0	TTGTTTATGTCTATGTCCCTGAAGCTGAATTTCGCTCATTTCTACTTTCT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	XA:Z:chr1,+43686,50M,2;	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:40
A00902:80:HL7Y2DRXX:2:2117:21468:10113	97	chr1	75812	35	50M	chr6	22223109	0	TTGTTTATGTCTATGTCCCTGAAGCTGAATTTCGCTCATTTCTACTTTCT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	XA:Z:chr1,+43686,50M,2;	MD:Z:50	PG:Z:MarkDuplicates	NM:i:0	AS:i:50	XS:i:40
A00902:80:HL7Y2DRXX:2:2261:22336:13369	161	chr1	77784	55	50M	=	78648	911	ACAACGGGTTTGAGAGAGCGCCGATAACAAAAGAATGAGTGAGAGCGATG	FF,F:FFF:,FF:,,F,FFFF,,,,:,F::,:FF,,:,F,F,FF:FF:,F	MD:Z:21A17G8A1	PG:Z:MarkDuplicates	NM:i:3	AS:i:38	XS:i:19
A00902:80:HL7Y2DRXX:2:2261:22336:13369	81	chr1	78648	60	47M	=	77784	-911	CCGAGGAGCAATCACTGACGCCACAGCCGAGCCGGCGCTTCACCAGC	F:FFFFFFFFF:F,F,FF,:FFFFFFFFFFFF:FF:F:F,FFFF,:F	MD:Z:18A28	PG:Z:MarkDuplicates	NM:i:1	AS:i:42	XS:i:0

Please let me know if you need any more information, and thank you for your time!

**Comment by taoliu** [comment]
It seems MACS2 can not read any valid read from BAM file. Could you check if there are any reads left after Picard MarkDuplicates, by running ` samtools flagstat` on the `H3K27ac_Skin_A.duplicate-removed.bam` file?

**Comment by NBKingsley** [comment]
@taoliu Thank you for your response! I did use flagstat like you recommended and the error was due to not having any properly paired reads (which after some troubleshooting appeared to be due to an issue in my filtering step). After fixing my filtering so that I did have properly paired reads, MACS2 seemed to process everything perfectly. Thank you again for your help!

**Comment by taoliu** [comment]
@NBKingsley You are welcome!
