### ISSUE TITLE
Huge memory usage of callpeak for earthworm genome

### ISSUE THREAD

**Issue by hunterchung** [taoliu/MACS#50]
I have some earthworm ChIP-seq samples. `MACS2 callpeak` needed a huge amount memory, and I got out of memory error for my server with **68GB** memory. I am not sure why, but I think it could be fixed.

**earthworm**

| Genome size | Effective genome size | ref genome scaffold/chromosome # | mapped reads # |
| --- | --- | --- | --- |
| 624328310 | 437029817  (genome size*0.7) | 7779940 | 477841 |

The output of `MACS2 callpeak`

```
INFO  @ Fri, 25 Jul 2014 16:38:21:
# Command line: callpeak -B -g 437029817 -t sample1.bam -c sample2.bam -n sample1_minus_control --nomodel --extsize 200
# ARGUMENTS LIST:
# name = sample1_minus_control
# format = AUTO
# ChIP-seq file = ['sample1.bam']
# control file = ['sample2.bam']
# effective genome size = 4.37e+08
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off

INFO  @ Fri, 25 Jul 2014 16:38:21: #1 read tag files...
INFO  @ Fri, 25 Jul 2014 16:38:21: #1 read treatment tags...
INFO  @ Fri, 25 Jul 2014 16:38:25: Detected format is: BAM
INFO  @ Fri, 25 Jul 2014 16:38:25: * Input file is gzipped.
INFO  @ Fri, 25 Jul 2014 16:38:38:  1000000
INFO  @ Fri, 25 Jul 2014 16:38:51:  2000000
INFO  @ Fri, 25 Jul 2014 16:39:07:  3000000
INFO  @ Fri, 25 Jul 2014 16:39:24:  4000000
INFO  @ Fri, 25 Jul 2014 16:39:43:  5000000
INFO  @ Fri, 25 Jul 2014 16:39:58:  6000000
comp.sh: line 1: 27146 Killed                  macs2 callpeak -B -g 437029817 -t sample1.bam -c sample2.bam -n sample1_minus_control --nomodel --extsize 200
```

**Comment by imk1** [comment]
I am having the same problem:
# effective genome size = 3.60e+09
# band width = 300
# model fold = [5, 50]
# pvalue cutoff = 1.00e-02
# qvalue will not be calculated and reported as -1 in the final output.
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is off
# MACS will save fragment pileup signal per million reads

INFO  @ Fri, 11 Jan 2019 11:37:33: #1 read tag files...
INFO  @ Fri, 11 Jan 2019 11:37:33: #1 read treatment tags...
INFO  @ Fri, 11 Jan 2019 11:37:37:  1000000
INFO  @ Fri, 11 Jan 2019 11:37:41:  2000000
INFO  @ Fri, 11 Jan 2019 11:37:45:  3000000
INFO  @ Fri, 11 Jan 2019 11:37:49:  4000000
INFO  @ Fri, 11 Jan 2019 11:37:53:  5000000
INFO  @ Fri, 11 Jan 2019 11:37:57:  6000000
INFO  @ Fri, 11 Jan 2019 11:38:01:  7000000
INFO  @ Fri, 11 Jan 2019 11:38:05:  8000000
INFO  @ Fri, 11 Jan 2019 11:38:10:  9000000
INFO  @ Fri, 11 Jan 2019 11:38:15:  10000000
INFO  @ Fri, 11 Jan 2019 11:38:21:  11000000
INFO  @ Fri, 11 Jan 2019 11:38:28:  12000000
INFO  @ Fri, 11 Jan 2019 11:38:32:  13000000
INFO  @ Fri, 11 Jan 2019 11:38:36:  14000000
INFO  @ Fri, 11 Jan 2019 11:38:40:  15000000
INFO  @ Fri, 11 Jan 2019 11:38:45:  16000000
INFO  @ Fri, 11 Jan 2019 11:38:49:  17000000
INFO  @ Fri, 11 Jan 2019 11:38:54:  18000000
INFO  @ Fri, 11 Jan 2019 11:38:59:  19000000
INFO  @ Fri, 11 Jan 2019 11:39:02:  20000000
Killed
I was using 80GB.  Is this a memory issue?

**Comment by taoliu** [comment]
Closing years old issues. Please reopen if you are still interested.
