### ISSUE TITLE
Diffpeak information?

### ISSUE THREAD

**Issue by nataliesilmon** [taoliu/MACS#63]
Hi, 

I would like to look at differential histone modifications between two different conditions. I have tried the Diffpeak option for this but can not find much information as to how it calculates differential binding (i.e. the log2-fold change column in the output xls file)and whether this is appropriate for histone modifications rather than transcription factors. I tried the command macs2 diffpeak --help but this doesn't answer my question. 

Also how do you specify two different sequencing depths? As my two samples have different depths. I tried -d depth_condition1 -d depth_condition2 but in the output xls file under "Depth multiplier", the value of the second depth is shown and not the first.

Many thanks

**Comment by taoliu** [comment]
Closing years old issues. Please reopen if you are still interested. PS: diffpeak was replaced by bdgdiff.
