### ISSUE TITLE
Differences between MACS version 2.0.10.20120913  and MACS version 2.1.0.20140616

### ISSUE THREAD

**Issue by medinaale** [taoliu/MACS#64]
Hello

We currently updated our server and this included updating MACs2 from 2.0.10.20120913 to 2.1.0.20140616 version.

We are analyzing ChIP-seq data for several histone marks and factors, after reanalyzing our ChiP-seq libraries with the most recent MACs2 version, we noticed a large discrepancy between MACS version 2.0.10.20120913  and MACS version 2.1.0.20140616. Specially for H3K27me, we called 100289 peaks with the older version, and 150541 with the newer version. Other marks called closer number of peaks. 

Command lines were exactly the same.

macs2 callpeak -t  chip-seq_read.bed.gz -c input_read.bed.gz  -f BED -g hs -q 0.05  -n out_chip-seq_peaks

Was there any major change in the algorithm between these two version that could be causing these difference?

Thanks for your help

Alejandra Medina

**Comment by taoliu** [comment]
Hi Alejandra,

H3K27me3 has a much weaker and broader profile in the genome, so please use 'macs2 callpeak --broad --broad-cutoff 0.1' to call the regions. The default behavior is for calling narrower factor such as transcription factor ChIP-Seq, and to call 'narrow regions' from a 'broad mark' will give unexpected results. 

Best,
Tao

**Comment by medinaale** [comment]
Hi Tao

Thanks for the recommendation. However, my question was regarding the changes that could have been made to the algorithm between version 2.010.20120913 and 2.1.020140616 that could cause that using the exact same parameter now I get such a high difference in peak number, I observe the same tendency when using the --broad option.

Thanks

Alejandra

**Comment by taoliu** [comment]
That's a long list of changes, with many bug fixes. Perhaps, some issues related to whether or not to call a peak just around cutoff value. 

If you pick up the most significant ones, they shouldn't differ a lot. If the big difference can only be found for this particular factor, then I would say that this factor is not appropriate to be treated in the default way.

**Comment by medinaale** [comment]
Thanks Tao

I see it with other histones as well. I understand the default values are not the best fit for all histones, the best sites have an overlap so they appear in both sets.

Thanks for your help.
Ale

**Comment by sowmyaiyer** [comment]
I see the same issue with my peak calls with --broad. ~70,000 peaks with version 2.1 and 15,000 peaks with version 2.0

**Comment by taoliu** [comment]
Closing years old issues. Please reopen if you are still interested. PS: Broad peak calling behavior has been adjusted recently.
