### ISSUE TITLE
Error installing MACS2 with Cython installed 

### ISSUE THREAD

**Issue by nicolazilio** [taoliu/MACS#69]
Dear all,

I am having a problem with installing MACS2 (v 2.1.0, downloaded on 25-Feb-2015). 

When I run 

    python setup.py install --prefix=/my/fav/folder

I get the following error. Cython, v 0.22 is installed. I know a similar issue was reposrted in issue #36, but no solution to the problem is provided there. Can anybody help? Thanks!

    running install
    /my/fav/folder/setuptools/lib/python2.7/site-packages/setuptools-12.2-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'distribute (0.6.24dev-r0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
    running bdist_egg
    running egg_info
    writing requirements to MACS2.egg-info/requires.txt
    writing MACS2.egg-info/PKG-INFO
    writing top-level names to MACS2.egg-info/top_level.txt
    writing dependency_links to MACS2.egg-info/dependency_links.txt
    writing requirements to MACS2.egg-info/requires.txt
    writing MACS2.egg-info/PKG-INFO
    writing top-level names to MACS2.egg-info/top_level.txt
    writing dependency_links to MACS2.egg-info/dependency_links.txt
    reading manifest file 'MACS2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'MANIFEST'
    writing manifest file 'MACS2.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    building 'MACS2.cProb' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 -c MACS2/cProb.c -o build/temp.linux-x86_64-2.7/MACS2/cProb.o -w -Ofast
    gcc: error: MACS2/cProb.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 4

**Comment by mdozmorov** [comment]
Response from Tao that helped me on CentOS:
>
A simple workaround although I don’t have CentOS to test: open MACS2 ‘setup.py’ file and replace all ‘-Ofast’ with ‘-O3’ or ‘-O2’. If it still doesn’t work, remove ‘-Ofast’ entirely.
>

**Comment by nicolazilio** [comment]
Thanks for the tip, but it didn’t work, with either –O3, -O2 or nothing. I don’t have a problem installing MACS (not version 2).

 

Nicola

**Comment by taoliu** [comment]
Hi Nicola,

Perhaps you downloaded incomplete source codes. Could you remove your current MACS2 source codes and old installation from your computer then download and try again?

-T

**Comment by nicolazilio** [comment]
Hey Tao,

 

I actually solved the issue in a much simpler way, I installed Anaconda to ensure all Python dependencies are satisfied and then did pip install. Worked without an issue.

 

Nicola

**Comment by taoliu** [comment]
@nicolazilio Good to know. Now I just closed this ticket.
