### ISSUE TITLE
handling replicates

### ISSUE THREAD

**Issue by mxenoph** [taoliu/MACS#70]
My colleague and I both separately installed macs2 2.1.0.20140616 (from `macs2 --version`) however our 2 installations seem to handle replicates for treatment/ChIP differently. According to `macs2 callpeak --help` one installation reads and combines files passed with `'-t A B C'` while the other treats the files as replicates using Liptak's method with weights.I have been trying to figure out why this is different if the versions are the same. In one case the version was installed from PyPI and in the other case from cloning the github repository.

Is it advisable to use the version on github or the official release? I would like to be able to use information from replicates and the release on PyPI is not doing that at the moment. Also can you direct me to any documentation about how replicates are weighted with Liptak's method?

**Comment by taoliu** [comment]
Hmm... Sorry, I believe I forgot to remove this description from macs2 command line! While files passed by '-t A B C', all three files will be simply pooled. There is no Liptak's method involved. There is another method in the current github version 'macs2 cmbreps' which can combine replicates using Fisher's method to combine p-values.

**Comment by taoliu** [comment]
Fixed in f614cafbc9c58ea520284b3fbf0e9f9ad3930d26

Sorry for the confusion!
