### ISSUE TITLE
Error with macs2 diffpeak

### ISSUE THREAD

**Issue by MosheOlshansky** [taoliu/MACS#72]
When I am trying to call it it can not find cDiffScore module. Below is what I get:

macs2 diffpeak --t1 noBPE_treat_pileup.bdg --t2 yesBPE_treat_pileup.bdg --c1 noBPE_control_lambda.bdg --c2 yesBPE_control_lambda.bdg -n no_vs_yes

Traceback (most recent call last):
  File "/software/MACS/MACS-2.1/bin/macs2", line 615, in <module>
    main()
  File "/software/MACS/MACS-2.1/bin/macs2", line 59, in main
    from MACS2.diffpeak import run
  File "/software/MACS/MACS-2.1/lib64/python2.7/site-packages/MACS2/diffpeak.py", line 31, in <module>
    from MACS2.IO.cDiffScore import DiffScoreTrackI
ImportError: No module named cDiffScore

Is there any way to fix this?

Thank you,
Moshe.

**Comment by taoliu** [comment]
'diffpeak' is obsolete.

**Comment by MosheOlshansky** [comment]
Dear Tao,

Thank you for your response.

Yesterday I tried to post a question to MACS Announcement but it looks like it wasn't posted. Below is the attempted post:

---------------------------------------------------------

Subject: the meaning of --broad-cutoff in MACS2

Hi everybody,

I understand that MACS2 decides which enriched regions to keep  (both with and without --broad) based on either p-value or q-value agains the combination (maximum) of global background lambda, large local lambda and small lambda obtained from control sample. Now, if --broad is specifies it combines these "raw" peaks which are within a certain distance of each other into a broad peak and them it decides whether to keep tis broad peak based on it's statistical significance. Is this correct?
If this is correct, how is that statistical significance for the broad peak computed? Moreover, if I want to use just p-value, why does it pre-cimpute the pvalue/qvalue table?

Thank you.
________________________________________

**Comment by taoliu** [comment]
@MosheOlshansky I closed this ticket.
