### ISSUE TITLE
ImportError with diffpeak

### ISSUE THREAD

**Issue by PikalaxALT** [taoliu/MACS#73]
When I tried to run MACS2 from a local library (~/.local/lib/python2.7/site-packages) on Python 2.7.9, I get the following error:

    $ macs2 diffpeak --t1 0956diff_1.ucsc.bedGraph --t2 0956lgr5_1.ucsc.bedGraph --c1 gen_1.ucsc.bedGraph --c2 gen_1.ucsc.bedGraph
    Traceback (most recent call last):
      File "/home/scnorton/.local/bin/macs2", line 559, in <module>
        main()
      File "/home/scnorton/.local/bin/macs2", line 59, in main
        from MACS2.diffpeak import run
      File "/home/scnorton/.local/lib/python2.7/site-packages/MACS2/diffpeak.py", line 31, in <module>
        from MACS2.IO.cDiffScore import DiffScoreTrackI
    ImportError: No module named cDiffScore
    
bdgdiff does not raise this error.

**Comment by taoliu** [comment]
'diffpeak' is obsolete.

**Comment by PikalaxALT** [comment]
Why is that not mentioned in the documentation?

- Scott Norton
scnorton@mail.med.upenn.edu

**Comment by taoliu** [comment]
Sorry about the confusion! It has been obsolete in the version I just uploaded to PyPI and also in our developing codes for a long time. I didn't have enough time to debug it in the last release back in 2014 so mistakenly left the unworkable diffpeak there.

**Comment by taoliu** [comment]
@PikalaxALT I closed this ticket.
