### ISSUE TITLE
Error updating MACS2 from PyPi with GCC 4.4.7 and Python 2.7.5

### ISSUE THREAD

**Issue by PikalaxALT** [taoliu/MACS#75]
Command input: `pip install --upgrade --user MACS2`

Last few lines of output:

    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/scnorton/.local/lib/python2.7/site-packages/numpy/core/include -I/opt/software/python/python-2.7.5/include/python2.7 -c MACS2/Prob.c -o build/temp.linux-x86_64-2.7/MACS2/Prob.o -w -Ofast
    
    cc1: error: invalid option argument ‘-Ofast’
    
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
      Rolling back uninstall of MACS2
    Cleaning up...
    Command /opt/software/python/python-2.7.5/bin/python -c "import setuptools;__file__='/tmp/pip_build_scnorton/MACS2/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3WIq2e-record/install-record.txt --single-version-externally-managed --user failed with error code 1 in /tmp/pip_build_scnorton/MACS2
    Traceback (most recent call last):
      File "/home/scnorton/.local/bin/pip", line 11, in <module>
        sys.exit(main())
      File "/opt/software/python/python-2.7.5/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/__init__.py", line 148, in main
        return command.main(args[1:], options)
      File "/opt/software/python/python-2.7.5/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 169, in main
        text = '\n'.join(complete_log)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 40: ordinal not in range(128)

**Comment by taoliu** [comment]
Hi PikalaxALT,

Perhaps GCC4.4.7 doesn't have Ofast option. You can download the source code by:

$ pip install MACS2 -d .
$ tar -zxvf MACS2-2.1.0.20150420.1.tar.gz
$ cd MACS2-2.1.0.20150420/

Then open the file setup.py and replace every -Ofast with -O3:

$ perl -pi -e 's/Ofast/O3/g' setup.py

Then:

$ python setup.py install

You may need to make sure you have permission to install new software. 

Best,
Tao

**Comment by dariober** [comment]
Hi- I stumbled across the very same problem and the fix suggested by Tao worked, thanks! I'd suggest adding a line in the INSTALL.rst file mentioning the requirement for gcc version and redirecting here if one cannot upgrade it.

Dario

**Comment by taoliu** [comment]
@dariober Will do so. Thanks for the suggestion!

**Comment by lparsons** [comment]
Just ran into this issue, didn't notice anything in the INSTALL.rst file. Any way to adjust this on the fly? Or maybe just use the more compatible -O3 flag? Otherwise, I'll have to add a patch during installs for CentOS6 systems.

**Comment by taoliu** [comment]
Check: cf84fb87
