### ISSUE TITLE
Broad peak calling and -p option

### ISSUE THREAD

**Issue by jgarthur** [taoliu/MACS#76]
I ran MACS2 (2.1.0.20140616) to call peaks on chromatin accessibility data (ATAC-seq) with the following options:

-t reads.bam -f BAM -g mm --nomodel --shift -100 --extsize 200 -p 1e-4 --broad

I wanted to check sensitivity to the p-value cutoff specified by -p (which I believe controls narrow peak calling before merging to broad peaks?). Running with, e.g., -p 1e-3 or -p 1e-10 gave identical output to the first run. The output is different than using -q 0.01, however. Is this the intended behavior?

**Comment by taoliu** [comment]
Hi Jgarthur,

Broad peak cutoff is controlled by '--broad-cutoff'. The '-p' option controls the narrower regions inside broad regions. BTW, in the newest release, there is a new tool to give you p-value cutoff analysis "macs2 callpeak --cutoff-analysis" (without using --broad mode). It will try pvalue cutoff from 1 to 1e-10 and collect how many peaks and bps can be called as enriched regions.  You may want to give it a try.

Best,
Tao

**Comment by jgarthur** [comment]
Tao,

Thanks for your suggestions.

Am I correct in saying that in --broad mode, the value set by -q or -p does not matter at all, but whether one sets -q or -p determines the meaning of --broad-cutoff as a q-value or p-value threshold?

**Comment by taoliu** [comment]
Yes. You are right. But -q or -p also determines the narrower calls inside broad regions. MACS2 broad mode does a 2-level peak calling and embed stronger/narrower calls in weaker/broader calls.

Thanks for reminding me this output issue. I will fix that so it will be displayed as  '#qvalue cutoff for narrow region = {x}' and '# qvalue cutoff for broad region = {y}' will be correctly displayed.

**Comment by taoliu** [comment]
Fixed in 49aa2b7

**Comment by koenvandenberge** [comment]
Dear Tao,

Above, you say that broad peak-calling runs through a two-step peak calling pipeline.
However, when calling broad peaks, the .broadPeak format only gives one list of peaks, which I am assuming are the broad peaks.
Is there a way to obtain the narrow peaks within the broad peaks, without re-running the pipeline excluding the --broad option?
