### ISSUE TITLE
bdgopt multiply function error. Usage?

### ISSUE THREAD

**Issue by damcpher** [taoliu/MACS#79]
Hello,

I was using MACS2 and ran across an issue with the command 'bdgopt'. I was trying to run this job in UNIX: 

macs2 bdgopt -i ShootMinus_treat_pileup.bdg -m multiply -p 0.59529055 -o ShtMinus.bdg 

to normalize read depth by multiplying my control ShtMinus by the ratio of the reads ShtPlus/ShtMinus. Instead it returned an error: 

AttributeError: 'Namespace' object has no attribute 'extparam'

Does anyone know if this is an usage error or if there is a workaround?

**Comment by taoliu** [comment]
Closed. Please reopen if you identify the issue again.
