### ISSUE TITLE
Error after installing with PIP

### ISSUE THREAD

**Issue by bcantarel** [taoliu/MACS#80]
I installed MACs with PIP after installation from source failed (for a failure to find installed NUMPY) -- now when I try to run macs2, I get the following error:

Traceback (most recent call last):
  File "/usr/bin/macs2", line 559, in <module>
    main()
  File "/usr/bin/macs2", line 55, in main
    from MACS2.callpeak import run
  File "/usr/lib/python2.7/site-packages/MACS2/callpeak.py", line 30, in <module>
    from MACS2.OptValidator import opt_validate
  File "/usr/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.cParser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 155, in init MACS2.IO.cParser (MACS2/IO/cParser.c:22531)
  File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/site-packages/numpy/core/__init__.py", line 46, in <module>
    from numpy.testing import Tester
  File "/usr/lib/python2.7/site-packages/numpy/testing/__init__.py", line 13, in <module>
    from .utils import *
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp
  File "/illumina/seqprg/anaconda/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/illumina/seqprg/anaconda/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/illumina/seqprg/anaconda/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'

**Comment by taoliu** [comment]
This is related to your python installation. I guess that you have two python -- one at /usr/lib and one at /illumina/seqprg/anaconda, so it caused some inconsistency.

**Comment by nbahlis** [comment]
I am having troubles installing MACS2 on a mac OSX 10.8.4. I keep getting the same error. I have reinstalled Numpy and Cython. Any advice. here's the error I get:
$ python setup_w_cython.py install
running install
running bdist_egg
running egg_info
writing requirements to MACS2.egg-info/requires.txt
writing MACS2.egg-info/PKG-INFO
writing top-level names to MACS2.egg-info/top_level.txt
writing dependency_links to MACS2.egg-info/dependency_links.txt
reading manifest file 'MACS2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'MANIFEST'
no previously-included directories found matching 'test'
writing manifest file 'MACS2.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-2.7
creating build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/bdgbroadcall_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/bdgcmp_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/bdgdiff_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/bdgopt_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/bdgpeakcall_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/callpeak_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/cmbreps_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/Constants.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/diffpeak_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/filterdup_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/OptValidator.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/OutputWriter.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/pileup_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/predictd_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/randsample_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
copying MACS2/refinepeak_cmd.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2
creating build/lib.macosx-10.5-x86_64-2.7/MACS2/IO
copying MACS2/IO/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2/IO
copying MACS2/IO/BinKeeper.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2/IO
copying MACS2/IO/test_processing.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2/IO
copying MACS2/IO/test_threading.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2/IO
creating build/lib.macosx-10.5-x86_64-2.7/MACS2/data
copying MACS2/data/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/MACS2/data
copying MACS2/data/g0.01.dat -> build/lib.macosx-10.5-x86_64-2.7/MACS2/data
copying MACS2/data/g0.05.dat -> build/lib.macosx-10.5-x86_64-2.7/MACS2/data
running build_ext
skipping 'MACS2/Prob.c' Cython extension (up-to-date)
building 'MACS2.Prob' extension
creating build/temp.macosx-10.5-x86_64-2.7
creating build/temp.macosx-10.5-x86_64-2.7/MACS2
/usr/bin/clang -fno-strict-aliasing -I//anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/lib/python2.7/site-packages/numpy/core/include -I//anaconda/include/python2.7 -c MACS2/Prob.c -o build/temp.macosx-10.5-x86_64-2.7/MACS2/Prob.o -w -Ofast
error: invalid integral value 'fast' in '-Ofast'
error: invalid integral value 'fast' in '-Ofast'
error: command '/usr/bin/clang' failed with exit status 1

**Comment by skurscheid** [comment]
"clang" is missing. This is the C/C++ compiler required for compiling the C code portions of MACS2. You are almost certainly missing Xcode on your Mac. At a minimum the command line tools are required:

https://developer.apple.com/library/ios/technotes/tn2339/_index.html

Try installing the command line tools, and if that not helps the complete Xcode package.

**Comment by taoliu** [comment]
@skurscheid Thanks for answering the question. 

Now I closed this ticket. If @bcantarel still has trouble to install, feel free to comment and discuss.
