### ISSUE TITLE
integer score for display

### ISSUE THREAD

**Issue by igordot** [taoliu/MACS#84]
I am looking at the .narrowPeak files generated by MACS. The 5th column is "integer score for display", which seems to correlate with -log10pvalue and -log10qvalue. Higher score is more significant, but what exactly does that score mean?

**Comment by taoliu** [comment]
The score is for 'display' purpose only. It's for UCSC browser and will make stronger peaks darker, and weaker peaks lighter. Check column 7-9 if you want meaningful values for your downstream analysis.

**Comment by taoliu** [comment]
Since it's not related to an issue of MACS codes, I closed the ticket. But you can still comment and discuss here.
