### ISSUE TITLE
stuck at pre-compute

### ISSUE THREAD

**Issue by duyphamuab** [taoliu/MACS#86]
Hi, 

I use macs2 2.1.0.20150420 version on ubuntu14.04. I have MACS2 installed on virtualenv. It takes forever (i am not sure it will end) at #3 pre-compute pvalue-qvalue table (if i remove --nolambda flag then it runs just fine). 

can you help? Thanks, 
Duy

This is what I did: 
# Command line: callpeak -t trial.bam -g mm --nomodel --nolambda --outdir /home/duypham/Desktop/trial/
# ARGUMENTS LIST:
# name = NA
# format = AUTO
# ChIP-seq file = ['trial.bam']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 read tag files... 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 read treatment tags... 
INFO  @ Fri, 03 Jul 2015 10:55:36: Detected format is: BAM 
INFO  @ Fri, 03 Jul 2015 10:55:36: * Input file is gzipped. 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 tag size is determined as 51 bps 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 tag size = 51 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1  total tags in treatment: 1260 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 user defined the maximum tags... 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1  tags after filtering in treatment: 1224 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1  Redundant rate of treatment: 0.03 
INFO  @ Fri, 03 Jul 2015 10:55:36: #1 finished! 
INFO  @ Fri, 03 Jul 2015 10:55:36: #2 Build Peak Model... 
INFO  @ Fri, 03 Jul 2015 10:55:36: #2 Skipped... 
INFO  @ Fri, 03 Jul 2015 10:55:36: #2 Use 200 as fragment length 
INFO  @ Fri, 03 Jul 2015 10:55:36: #3 Call peaks... 
INFO  @ Fri, 03 Jul 2015 10:55:36: # local lambda is disabled! 
INFO  @ Fri, 03 Jul 2015 10:55:36: #3 !!!! DYNAMIC LAMBDA IS DISABLED !!!! 
INFO  @ Fri, 03 Jul 2015 10:55:36: #3 Pre-compute pvalue-qvalue table...

**Comment by taoliu** [comment]
@duyphamuab, do you mind send me the Trial.bam file? I will try to reproduce this issue.

**Comment by duyphamuab** [comment]
Please see the attached file for trial.bam.gz
Thanks, 
Duy 


     On Monday, July 27, 2015 11:40 AM, Tao Liu (τν) <notifications@github.com> wrote:
   

 @duyphamuab, do you mind send me the Trial.bam file? I will try to reproduce this issue.—

**Comment by taoliu** [comment]
@duyphamuab I can't see your attachment. Could you pass it to me using dropbox? You can send it to my gmail address. Open ChangeLog file and you will see my address.

**Comment by taoliu** [comment]
Fixed. It turns out I wrongly used 'ndarray' to initialize a new Numpy array. Should use 'array' function instead. Thanks for the report!

**Comment by duyphamuab** [comment]
Thanks!

**Comment by MisterMorris** [comment]
I got exactly the same problem.
I rewrote the lines in PeakDetect.pyx, but the problem wasn´t fixed.
Is it necessary rewrite PeakDetect.c? or delete it?

**Comment by gireeshkbogu** [comment]
I still this problem with version macs2 2.1.1.20160309. How can I fix this? thanks

**Comment by taoliu** [comment]
@gireeshkbogu Still have the same problem? Could you provide some detail? Also make sure the correct version is used. Sometimes, old version (e.g. old MACS2 libraries) and new version (e.g. new MACS2 executables) may be incorrectly mixed.

**Comment by sklasfeld** [comment]
I too am getting stalling at the same point. I am using a BED file (converted from a BAM file) with about 38 million lines. I am running the default parameters, however, when I use `--keep-dup auto` it runs and keeps 7 duplicates.

**Comment by sklasfeld** [comment]
I continue to get this issue. This time I am using normal bam files.
