### ISSUE TITLE
control lambda bedGraph

### ISSUE THREAD

**Issue by igordot** [taoliu/MACS#90]
The best description of lambda I could find (https://groups.google.com/forum/#!msg/macs-announcement/JkufzGpUNRk/kUx0z2M2b_cJ):
> For each peak region, MACS calculates the a local lambda for poisson
> distribution based on the control tags within the 1kb, 5kb and
> 10kb(1/5/10k are parameters that you can modify) nearby regions to
> consider the local fluctuations and biases. The local lambda is the
> maximum of the averages of tags for 1/5/10 kb regions and a whole
> genome background. Then this local lambda is used to calculate the p-
> value of poisson distribution.

With the --bdg parameter, I can output control_lambda.bdg files. If lambda is calculated locally, how is that translated into bedGraph peaks or are those showing something else entirely? Also, if lambda is calculated around peak regions, shouldn't most of the genome not have any values then?

**Comment by taoliu** [comment]
@igordot The lambda values are calculated at every positions along the whole genome, not only the peak regions. The _control_lambda bedGraph can be regarded as the estimated local bias from control library. Then MACS2 will compare the values in _treat_pileup (as observation) and _control_lambda (as lambda in Poisson model) bedGraph files to find the enriched sites. 

Since it's not related to an issue of MACS codes, I closed the ticket. But you can still comment and discuss here.

**Comment by igordot** [comment]
Thank you for the clarification. The reason I ask is I ran into an issue with those files. Usually, they make sense. However, now I have an experiment with multiple groups. Overall, the samples look fairly similar in terms of number of reads and duplicates. I ran MACS using replicates, so the bedGraph output are for groups. Looking at the raw pileups (derived from the BAMs), all the inputs look similar, but the lambda values for one of the groups is much lower than those for the rest of the groups. It's also the same group where no peaks were called despite over 50,000 peaks called for all other groups. So if the pileups for inputs look similar, why do the lambda pileups look so different? Could that be related to lack of significant peaks?

**Comment by taoliu** [comment]
@igordot No, it's not related to peaks at all. Lambda values are computed before calling peaks. The lambda values should match to the corresponding IP data, since there is a linear scaling step to downscale the larger sample size to match the smaller one ( the default and recommended behavior of MACS2 without setting --to-large). So if one of your IP has very few reads, but your control is much larger, the values in __control_lambda will be scaled down more. Does the IP of that replicate with no peak calls look similar to other replicates?

**Comment by igordot** [comment]
All my samples are roughly even in terms of reads. They all have over 15M reads, even after duplicate removal, which should be sufficient. Even before worrying about treatment samples, why do the lambda pileups differ even though the inputs look similar? Treatment samples should not affect that, right?

**Comment by taoliu** [comment]
@igordot As I mentioned, the larger sample will be scaled down. So if control is bigger, then the lambda values will be divided by the ratio of control/IP. Also, MACS2 don't consider all the reads you have in the BAM file, those with certain flags will be discarded such as '0x4 segment unmapped'. Furthermore those duplicate reads will be removed if the default '--keep-dup 1' is not set to other values.  You'd better check the actual numbers from the MACS2 output 'xls' file or runtime message. Check

"tags after filtering in treatment:"

and 

"tags after filtering in control:"

**Comment by igordot** [comment]
Here is my tag info for each of the four groups.
```
# tag size is determined as 51 bps
# total tags in treatment: 76292353
# tags after filtering in treatment: 73095608
# maximum duplicate tags at the same position in treatment = 1
# Redundant rate in treatment: 0.04
# total tags in control: 71218401
# tags after filtering in control: 68696949
# maximum duplicate tags at the same position in control = 1
# Redundant rate in control: 0.04
# d = 189

# tag size is determined as 51 bps
# total tags in treatment: 63207222
# tags after filtering in treatment: 60270654
# maximum duplicate tags at the same position in treatment = 1
# Redundant rate in treatment: 0.05
# total tags in control: 71875484
# tags after filtering in control: 69314434
# maximum duplicate tags at the same position in control = 1
# Redundant rate in control: 0.04
# d = 192

# tag size is determined as 51 bps
# total tags in treatment: 107769460
# tags after filtering in treatment: 96019127
# maximum duplicate tags at the same position in treatment = 1
# Redundant rate in treatment: 0.11
# total tags in control: 75155470
# tags after filtering in control: 72076165
# maximum duplicate tags at the same position in control = 1
# Redundant rate in control: 0.04
# d = 175

# tag size is determined as 51 bps
# total tags in treatment: 122820212
# tags after filtering in treatment: 114023016
# maximum duplicate tags at the same position in treatment = 1
# Redundant rate in treatment: 0.07
# total tags in control: 90586783
# tags after filtering in control: 86140307
# maximum duplicate tags at the same position in control = 1
# Redundant rate in control: 0.05
# d = 50
```
I think they look similar. What jumps out at me is the "d". I think that is fragment length. Could that be the problem?

**Comment by taoliu** [comment]
Yes. 'd' would influence the pileup and control_lambda as well. Basically, if the maximum duplicate tag is 1, then if d=100, the maximum pileup will be 200 (plus+minus strand), and if d=50, the maximum will be 100. A d=50 from cross-correlation which is similar to the read length (tag size) indicates that replicate may have quality issue. Google 'phantom peak' to see the detail. By the way, did MACS2 give you other 'alternative d'?

**Comment by igordot** [comment]
Yes, I think there was definitely a quality issue. I got alternative fragment lengths, but if you look at the cross-correlation graph, they look very weak (187 seems real considering that's what I see with the other samples are):
![image](https://cloud.githubusercontent.com/assets/6363505/9013499/64a4c1dc-378a-11e5-8d88-c019577ffc89.png)

**Comment by taoliu** [comment]
@igordot Agree. 187 must be a more appropriate number. And this plot definitely raised a flag of poor quality data. But if you still want to use this replicate, use '--nomodel --ext 187'.

**Comment by igordot** [comment]
If the estimated model is so bad, is it even a good trying to adjust it? I believe that the results will improve, but would they be trustable?

**Comment by laijen000** [comment]
Hi @taoliu, 
Thank you for this wonderful tool! If I want to visualize the treatment v. control tracks on UCSC genome browser or IGV, is it appropriate to use the treat_pileup.bdg and control_lambda.bdg as is? Is the "control_lambda.bdg" showing the peaks that are present in the background? 

Thank you!

**Comment by taoliu** [comment]
@laijen000 You can use them as is or use the `bdgcmp` subcommand to combine the two tracks to make a foldchange or p-value track. The control_lambda.bdg can not show you the 'peaks' in the background since the values in it are representing a maximum 'local bias' taking into consideration regions of different sizes of 1,000bp, 10,000bp, and global background. If you plan to check 'peaks' in the background, try to use control file for '-t' while calling peaks.
