### ISSUE TITLE
macs2: error: no such option: --call-summits

### ISSUE THREAD

**Issue by brianpenghe** [taoliu/MACS#98]
I ran 
macs2 callpeak -f BAM -t 84330.unique.bam -n 84330.unique -g mm -B -q 0.01 --call-summits 
But it said macs2: error: no such option: --call-summits

What's the reason?

**Comment by brianpenghe** [comment]
also
macs2: error: no such option: --outdir

**Comment by taoliu** [comment]
Normally, that means you have mixed a new 'macs2' executable script with an old MACS2 library. Try to remove your old installation ENTIRELY and reinstall.

**Comment by taoliu** [comment]
Closed due to inactivity. Reopen if needed.
